#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct EventType(pub u16);

#[allow(non_upper_case_globals)]
#[allow(dead_code)]
impl EventType {
    pub const evUnused: EventType = EventType(0);
    pub const evLeave: EventType = EventType(1);
    pub const evJoinFinished: EventType = EventType(2);
    pub const evMove: EventType = EventType(3);
    pub const evTeleport: EventType = EventType(4);
    pub const evChangeEquipment: EventType = EventType(5);
    pub const evHealthUpdate: EventType = EventType(6);
    pub const evHealthUpdates: EventType = EventType(7);
    pub const evEnergyUpdate: EventType = EventType(8);
    pub const evDamageShieldUpdate: EventType = EventType(9);
    pub const evCraftingFocusUpdate: EventType = EventType(10);
    pub const evActiveSpellEffectsUpdate: EventType = EventType(11);
    pub const evResetCooldowns: EventType = EventType(12);
    pub const evAttack: EventType = EventType(13);
    pub const evCastStart: EventType = EventType(14);
    pub const evChannelingUpdate: EventType = EventType(15);
    pub const evCastCancel: EventType = EventType(16);
    pub const evCastTimeUpdate: EventType = EventType(17);
    pub const evCastFinished: EventType = EventType(18);
    pub const evCastSpell: EventType = EventType(19);
    pub const evCastSpells: EventType = EventType(20);
    pub const evCastHit: EventType = EventType(21);
    pub const evCastHits: EventType = EventType(22);
    pub const evStoredTargetsUpdate: EventType = EventType(23);
    pub const evChannelingEnded: EventType = EventType(24);
    pub const evAttackBuilding: EventType = EventType(25);
    pub const evInventoryPutItem: EventType = EventType(26);
    pub const evInventoryDeleteItem: EventType = EventType(27);
    pub const evInventoryState: EventType = EventType(28);
    pub const evNewCharacter: EventType = EventType(29);
    pub const evNewEquipmentItem: EventType = EventType(30);
    pub const evNewSiegeBannerItem: EventType = EventType(31);
    pub const evNewSimpleItem: EventType = EventType(32);
    pub const evNewFurnitureItem: EventType = EventType(33);
    pub const evNewKillTrophyItem: EventType = EventType(34);
    pub const evNewJournalItem: EventType = EventType(35);
    pub const evNewLaborerItem: EventType = EventType(36);
    pub const evNewEquipmentItemLegendarySoul: EventType = EventType(37);
    pub const evNewSimpleHarvestableObject: EventType = EventType(38);
    pub const evNewSimpleHarvestableObjectList: EventType = EventType(39);
    pub const evNewHarvestableObject: EventType = EventType(40);
    pub const evNewTreasureDestinationObject: EventType = EventType(41);
    pub const evTreasureDestinationObjectStatus: EventType = EventType(42);
    pub const evCloseTreasureDestinationObject: EventType = EventType(43);
    pub const evNewSilverObject: EventType = EventType(44);
    pub const evNewBuilding: EventType = EventType(45);
    pub const evHarvestableChangeState: EventType = EventType(46);
    pub const evMobChangeState: EventType = EventType(47);
    pub const evFactionBuildingInfo: EventType = EventType(48);
    pub const evCraftBuildingInfo: EventType = EventType(49);
    pub const evRepairBuildingInfo: EventType = EventType(50);
    pub const evMeldBuildingInfo: EventType = EventType(51);
    pub const evConstructionSiteInfo: EventType = EventType(52);
    pub const evPlayerBuildingInfo: EventType = EventType(53);
    pub const evFarmBuildingInfo: EventType = EventType(54);
    pub const evTutorialBuildingInfo: EventType = EventType(55);
    pub const evLaborerObjectInfo: EventType = EventType(56);
    pub const evLaborerObjectJobInfo: EventType = EventType(57);
    pub const evMarketPlaceBuildingInfo: EventType = EventType(58);
    pub const evHarvestStart: EventType = EventType(59);
    pub const evHarvestCancel: EventType = EventType(60);
    pub const evHarvestFinished: EventType = EventType(61);
    pub const evTakeSilver: EventType = EventType(62);
    pub const evRemoveSilver: EventType = EventType(63);
    pub const evActionOnBuildingStart: EventType = EventType(64);
    pub const evActionOnBuildingCancel: EventType = EventType(65);
    pub const evActionOnBuildingFinished: EventType = EventType(66);
    pub const evItemRerollQualityFinished: EventType = EventType(67);
    pub const evInstallResourceStart: EventType = EventType(68);
    pub const evInstallResourceCancel: EventType = EventType(69);
    pub const evInstallResourceFinished: EventType = EventType(70);
    pub const evCraftItemFinished: EventType = EventType(71);
    pub const evLogoutCancel: EventType = EventType(72);
    pub const evChatMessage: EventType = EventType(73);
    pub const evChatSay: EventType = EventType(74);
    pub const evChatWhisper: EventType = EventType(75);
    pub const evChatMuted: EventType = EventType(76);
    pub const evPlayEmote: EventType = EventType(77);
    pub const evStopEmote: EventType = EventType(78);
    pub const evSystemMessage: EventType = EventType(79);
    pub const evUtilityTextMessage: EventType = EventType(80);
    pub const evUpdateMoney: EventType = EventType(81);
    pub const evUpdateFame: EventType = EventType(82);
    pub const evUpdateLearningPoints: EventType = EventType(83);
    pub const evUpdateReSpecPoints: EventType = EventType(84);
    pub const evUpdateCurrency: EventType = EventType(85);
    pub const evUpdateFactionStanding: EventType = EventType(86);
    pub const evUpdateStanding: EventType = EventType(87);
    pub const evRespawn: EventType = EventType(88);
    pub const evServerDebugLog: EventType = EventType(89);
    pub const evCharacterEquipmentChanged: EventType = EventType(90);
    pub const evRegenerationHealthChanged: EventType = EventType(91);
    pub const evRegenerationEnergyChanged: EventType = EventType(92);
    pub const evRegenerationMountHealthChanged: EventType = EventType(93);
    pub const evRegenerationCraftingChanged: EventType = EventType(94);
    pub const evRegenerationHealthEnergyComboChanged: EventType = EventType(95);
    pub const evRegenerationPlayerComboChanged: EventType = EventType(96);
    pub const evDurabilityChanged: EventType = EventType(97);
    pub const evNewLoot: EventType = EventType(98);
    pub const evAttachItemContainer: EventType = EventType(99);
    pub const evDetachItemContainer: EventType = EventType(100);
    pub const evInvalidateItemContainer: EventType = EventType(101);
    pub const evLockItemContainer: EventType = EventType(102);
    pub const evGuildUpdate: EventType = EventType(103);
    pub const evGuildPlayerUpdated: EventType = EventType(104);
    pub const evInvitedToGuild: EventType = EventType(105);
    pub const evGuildMemberWorldUpdate: EventType = EventType(106);
    pub const evUpdateMatchDetails: EventType = EventType(107);
    pub const evObjectEvent: EventType = EventType(108);
    pub const evNewMonolithObject: EventType = EventType(109);
    pub const evMonolithHasBannersPlacedUpdate: EventType = EventType(110);
    pub const evNewOrbObject: EventType = EventType(111);
    pub const evNewCastleObject: EventType = EventType(112);
    pub const evNewSpellEffectArea: EventType = EventType(113);
    pub const evUpdateSpellEffectArea: EventType = EventType(114);
    pub const evNewChainSpell: EventType = EventType(115);
    pub const evUpdateChainSpell: EventType = EventType(116);
    pub const evNewTreasureChest: EventType = EventType(117);
    pub const evStartMatch: EventType = EventType(118);
    pub const evStartArenaMatchInfos: EventType = EventType(119);
    pub const evEndArenaMatch: EventType = EventType(120);
    pub const evMatchUpdate: EventType = EventType(121);
    pub const evActiveMatchUpdate: EventType = EventType(122);
    pub const evNewMob: EventType = EventType(123);
    pub const evDebugMobInfo: EventType = EventType(124);
    pub const evDebugVariablesInfo: EventType = EventType(125);
    pub const evDebugReputationInfo: EventType = EventType(126);
    pub const evDebugDiminishingReturnInfo: EventType = EventType(127);
    pub const evDebugSmartClusterQueueInfo: EventType = EventType(128);
    pub const evClaimOrbStart: EventType = EventType(129);
    pub const evClaimOrbFinished: EventType = EventType(130);
    pub const evClaimOrbCancel: EventType = EventType(131);
    pub const evOrbUpdate: EventType = EventType(132);
    pub const evOrbClaimed: EventType = EventType(133);
    pub const evOrbReset: EventType = EventType(134);
    pub const evNewWarCampObject: EventType = EventType(135);
    pub const evNewMatchLootChestObject: EventType = EventType(136);
    pub const evNewArenaExit: EventType = EventType(137);
    pub const evGuildMemberTerritoryUpdate: EventType = EventType(138);
    pub const evInvitedMercenaryToMatch: EventType = EventType(139);
    pub const evClusterInfoUpdate: EventType = EventType(140);
    pub const evForcedMovement: EventType = EventType(141);
    pub const evForcedMovementCancel: EventType = EventType(142);
    pub const evCharacterStats: EventType = EventType(143);
    pub const evCharacterStatsKillHistory: EventType = EventType(144);
    pub const evCharacterStatsDeathHistory: EventType = EventType(145);
    pub const evCharacterStatsKnockDownHistory: EventType = EventType(146);
    pub const evCharacterStatsKnockedDownHistory: EventType = EventType(147);
    pub const evGuildStats: EventType = EventType(148);
    pub const evKillHistoryDetails: EventType = EventType(149);
    pub const evItemKillHistoryDetails: EventType = EventType(150);
    pub const evFullAchievementInfo: EventType = EventType(151);
    pub const evFinishedAchievement: EventType = EventType(152);
    pub const evAchievementProgressInfo: EventType = EventType(153);
    pub const evFullAchievementProgressInfo: EventType = EventType(154);
    pub const evFullTrackedAchievementInfo: EventType = EventType(155);
    pub const evFullAutoLearnAchievementInfo: EventType = EventType(156);
    pub const evQuestGiverQuestOffered: EventType = EventType(157);
    pub const evQuestGiverDebugInfo: EventType = EventType(158);
    pub const evConsoleEvent: EventType = EventType(159);
    pub const evTimeSync: EventType = EventType(160);
    pub const evChangeAvatar: EventType = EventType(161);
    pub const evChangeMountSkin: EventType = EventType(162);
    pub const evGameEvent: EventType = EventType(163);
    pub const evKilledPlayer: EventType = EventType(164);
    pub const evDied: EventType = EventType(165);
    pub const evKnockedDown: EventType = EventType(166);
    pub const evUnconcious: EventType = EventType(167);
    pub const evMatchPlayerJoinedEvent: EventType = EventType(168);
    pub const evMatchPlayerStatsEvent: EventType = EventType(169);
    pub const evMatchPlayerStatsCompleteEvent: EventType = EventType(170);
    pub const evMatchTimeLineEventEvent: EventType = EventType(171);
    pub const evMatchNewCombatRound: EventType = EventType(172);
    pub const evMatchEndCombatRound: EventType = EventType(173);
    pub const evMatchPlayerMainGearStatsEvent: EventType = EventType(174);
    pub const evMatchPlayerChangedAvatarEvent: EventType = EventType(175);
    pub const evInvitationPlayerTrade: EventType = EventType(176);
    pub const evPlayerTradeStart: EventType = EventType(177);
    pub const evPlayerTradeCancel: EventType = EventType(178);
    pub const evPlayerTradeUpdate: EventType = EventType(179);
    pub const evPlayerTradeFinished: EventType = EventType(180);
    pub const evPlayerTradeAcceptChange: EventType = EventType(181);
    pub const evMiniMapPing: EventType = EventType(182);
    pub const evMarketPlaceNotification: EventType = EventType(183);
    pub const evDuellingChallengePlayer: EventType = EventType(184);
    pub const evNewDuellingPost: EventType = EventType(185);
    pub const evDuelStarted: EventType = EventType(186);
    pub const evDuelEnded: EventType = EventType(187);
    pub const evDuelDenied: EventType = EventType(188);
    pub const evDuelRequestCanceled: EventType = EventType(189);
    pub const evDuelLeftArea: EventType = EventType(190);
    pub const evDuelReEnteredArea: EventType = EventType(191);
    pub const evNewRealEstate: EventType = EventType(192);
    pub const evMiniMapOwnedBuildingsPositions: EventType = EventType(193);
    pub const evRealEstateListUpdate: EventType = EventType(194);
    pub const evGuildLogoUpdate: EventType = EventType(195);
    pub const evGuildLogoChanged: EventType = EventType(196);
    pub const evPlaceableObjectPlace: EventType = EventType(197);
    pub const evPlaceableObjectPlaceCancel: EventType = EventType(198);
    pub const evFurnitureObjectBuffProviderInfo: EventType = EventType(199);
    pub const evFurnitureObjectCheatProviderInfo: EventType = EventType(200);
    pub const evFarmableObjectInfo: EventType = EventType(201);
    pub const evNewUnreadMails: EventType = EventType(202);
    pub const evMailOperationPossible: EventType = EventType(203);
    pub const evGuildLogoObjectUpdate: EventType = EventType(204);
    pub const evStartLogout: EventType = EventType(205);
    pub const evNewChatChannels: EventType = EventType(206);
    pub const evJoinedChatChannel: EventType = EventType(207);
    pub const evLeftChatChannel: EventType = EventType(208);
    pub const evRemovedChatChannel: EventType = EventType(209);
    pub const evAccessStatus: EventType = EventType(210);
    pub const evMounted: EventType = EventType(211);
    pub const evMountStart: EventType = EventType(212);
    pub const evMountCancel: EventType = EventType(213);
    pub const evNewTravelpoint: EventType = EventType(214);
    pub const evNewIslandAccessPoint: EventType = EventType(215);
    pub const evNewExit: EventType = EventType(216);
    pub const evUpdateHome: EventType = EventType(217);
    pub const evUpdateChatSettings: EventType = EventType(218);
    pub const evResurrectionOffer: EventType = EventType(219);
    pub const evResurrectionReply: EventType = EventType(220);
    pub const evLootEquipmentChanged: EventType = EventType(221);
    pub const evUpdateUnlockedGuildLogos: EventType = EventType(222);
    pub const evUpdateUnlockedAvatars: EventType = EventType(223);
    pub const evUpdateUnlockedAvatarRings: EventType = EventType(224);
    pub const evUpdateUnlockedBuildings: EventType = EventType(225);
    pub const evNewIslandManagement: EventType = EventType(226);
    pub const evNewTeleportStone: EventType = EventType(227);
    pub const evCloak: EventType = EventType(228);
    pub const evPartyInvitation: EventType = EventType(229);
    pub const evPartyJoinRequest: EventType = EventType(230);
    pub const evPartyJoined: EventType = EventType(231);
    pub const evPartyDisbanded: EventType = EventType(232);
    pub const evPartyPlayerJoined: EventType = EventType(233);
    pub const evPartyChangedOrder: EventType = EventType(234);
    pub const evPartyPlayerLeft: EventType = EventType(235);
    pub const evPartyLeaderChanged: EventType = EventType(236);
    pub const evPartyLootSettingChangedPlayer: EventType = EventType(237);
    pub const evPartySilverGained: EventType = EventType(238);
    pub const evPartyPlayerUpdated: EventType = EventType(239);
    pub const evPartyInvitationAnswer: EventType = EventType(240);
    pub const evPartyJoinRequestAnswer: EventType = EventType(241);
    pub const evPartyMarkedObjectsUpdated: EventType = EventType(242);
    pub const evPartyOnClusterPartyJoined: EventType = EventType(243);
    pub const evPartySetRoleFlag: EventType = EventType(244);
    pub const evPartyInviteOrJoinPlayerEquipmentInfo: EventType = EventType(245);
    pub const evPartyReadyCheckUpdate: EventType = EventType(246);
    pub const evPartyFactionWarfareReinforcementSettingChangedPlayer: EventType = EventType(247);
    pub const evSpellCooldownUpdate: EventType = EventType(248);
    pub const evNewHellgateExitPortal: EventType = EventType(249);
    pub const evNewExpeditionExit: EventType = EventType(250);
    pub const evNewExpeditionNarrator: EventType = EventType(251);
    pub const evExitEnterStart: EventType = EventType(252);
    pub const evExitEnterCancel: EventType = EventType(253);
    pub const evExitEnterFinished: EventType = EventType(254);
    pub const evNewQuestGiverObject: EventType = EventType(255);
    pub const evFullQuestInfo: EventType = EventType(256);
    pub const evQuestProgressInfo: EventType = EventType(257);
    pub const evQuestGiverInfoForPlayer: EventType = EventType(258);
    pub const evFullExpeditionInfo: EventType = EventType(259);
    pub const evExpeditionQuestProgressInfo: EventType = EventType(260);
    pub const evInvitedToExpedition: EventType = EventType(261);
    pub const evExpeditionRegistrationInfo: EventType = EventType(262);
    pub const evEnteringExpeditionStart: EventType = EventType(263);
    pub const evEnteringExpeditionCancel: EventType = EventType(264);
    pub const evRewardGranted: EventType = EventType(265);
    pub const evArenaRegistrationInfo: EventType = EventType(266);
    pub const evEnteringArenaStart: EventType = EventType(267);
    pub const evEnteringArenaCancel: EventType = EventType(268);
    pub const evEnteringArenaLockStart: EventType = EventType(269);
    pub const evEnteringArenaLockCancel: EventType = EventType(270);
    pub const evInvitedToArenaMatch: EventType = EventType(271);
    pub const evUsingHellgateShrine: EventType = EventType(272);
    pub const evEnteringHellgateLockStart: EventType = EventType(273);
    pub const evEnteringHellgateLockCancel: EventType = EventType(274);
    pub const evPlayerCounts: EventType = EventType(275);
    pub const evInCombatStateUpdate: EventType = EventType(276);
    pub const evOtherGrabbedLoot: EventType = EventType(277);
    pub const evTreasureChestUsingStart: EventType = EventType(278);
    pub const evTreasureChestUsingFinished: EventType = EventType(279);
    pub const evTreasureChestUsingCancel: EventType = EventType(280);
    pub const evTreasureChestUsingOpeningComplete: EventType = EventType(281);
    pub const evTreasureChestForceCloseInventory: EventType = EventType(282);
    pub const evLocalTreasuresUpdate: EventType = EventType(283);
    pub const evLootChestSpawnpointsUpdate: EventType = EventType(284);
    pub const evPremiumChanged: EventType = EventType(285);
    pub const evPremiumExtended: EventType = EventType(286);
    pub const evPremiumLifeTimeRewardGained: EventType = EventType(287);
    pub const evGoldPurchased: EventType = EventType(288);
    pub const evLaborerGotUpgraded: EventType = EventType(289);
    pub const evJournalGotFull: EventType = EventType(290);
    pub const evJournalFillError: EventType = EventType(291);
    pub const evFriendRequest: EventType = EventType(292);
    pub const evFriendRequestInfos: EventType = EventType(293);
    pub const evFriendInfos: EventType = EventType(294);
    pub const evFriendRequestAnswered: EventType = EventType(295);
    pub const evFriendOnlineStatus: EventType = EventType(296);
    pub const evFriendRequestCanceled: EventType = EventType(297);
    pub const evFriendRemoved: EventType = EventType(298);
    pub const evFriendUpdated: EventType = EventType(299);
    pub const evPartyLootItems: EventType = EventType(300);
    pub const evPartyLootItemsRemoved: EventType = EventType(301);
    pub const evPartyLootItemTypesRemoved: EventType = EventType(302);
    pub const evReputationUpdate: EventType = EventType(303);
    pub const evDefenseUnitAttackBegin: EventType = EventType(304);
    pub const evDefenseUnitAttackEnd: EventType = EventType(305);
    pub const evDefenseUnitAttackDamage: EventType = EventType(306);
    pub const evUnrestrictedPvpZoneUpdate: EventType = EventType(307);
    pub const evUnrestrictedPvpZoneStatus: EventType = EventType(308);
    pub const evReputationImplicationUpdate: EventType = EventType(309);
    pub const evNewMountObject: EventType = EventType(310);
    pub const evMountHealthUpdate: EventType = EventType(311);
    pub const evMountCooldownUpdate: EventType = EventType(312);
    pub const evNewExpeditionAgent: EventType = EventType(313);
    pub const evNewExpeditionCheckPoint: EventType = EventType(314);
    pub const evExpeditionStartEvent: EventType = EventType(315);
    pub const evVoteEvent: EventType = EventType(316);
    pub const evRatingEvent: EventType = EventType(317);
    pub const evNewArenaAgent: EventType = EventType(318);
    pub const evBoostFarmable: EventType = EventType(319);
    pub const evUseFunction: EventType = EventType(320);
    pub const evNewPortalEntrance: EventType = EventType(321);
    pub const evNewPortalExit: EventType = EventType(322);
    pub const evNewRandomDungeonExit: EventType = EventType(323);
    pub const evWaitingQueueUpdate: EventType = EventType(324);
    pub const evPlayerMovementRateUpdate: EventType = EventType(325);
    pub const evObserveStart: EventType = EventType(326);
    pub const evMinimapZergs: EventType = EventType(327);
    pub const evMinimapSmartClusterZergs: EventType = EventType(328);
    pub const evPaymentTransactions: EventType = EventType(329);
    pub const evPerformanceStatsUpdate: EventType = EventType(330);
    pub const evOverloadModeUpdate: EventType = EventType(331);
    pub const evDebugDrawEvent: EventType = EventType(332);
    pub const evRecordCameraMove: EventType = EventType(333);
    pub const evRecordStart: EventType = EventType(334);
    pub const evDeliverCarriableObjectStart: EventType = EventType(335);
    pub const evDeliverCarriableObjectCancel: EventType = EventType(336);
    pub const evDeliverCarriableObjectReset: EventType = EventType(337);
    pub const evDeliverCarriableObjectFinished: EventType = EventType(338);
    pub const evTerritoryClaimStart: EventType = EventType(339);
    pub const evTerritoryClaimCancel: EventType = EventType(340);
    pub const evTerritoryClaimFinished: EventType = EventType(341);
    pub const evTerritoryScheduleResult: EventType = EventType(342);
    pub const evTerritoryUpgradeWithPowerCrystalResult: EventType = EventType(343);
    pub const evReceiveCarriableObjectStart: EventType = EventType(344);
    pub const evReceiveCarriableObjectFinished: EventType = EventType(345);
    pub const evUpdateAccountState: EventType = EventType(346);
    pub const evStartDeterministicRoam: EventType = EventType(347);
    pub const evGuildFullAccessTagsUpdated: EventType = EventType(348);
    pub const evGuildAccessTagUpdated: EventType = EventType(349);
    pub const evGvgSeasonUpdate: EventType = EventType(350);
    pub const evGvgSeasonCheatCommand: EventType = EventType(351);
    pub const evSeasonPointsByKillingBooster: EventType = EventType(352);
    pub const evFishingStart: EventType = EventType(353);
    pub const evFishingCast: EventType = EventType(354);
    pub const evFishingCatch: EventType = EventType(355);
    pub const evFishingFinished: EventType = EventType(356);
    pub const evFishingCancel: EventType = EventType(357);
    pub const evNewFloatObject: EventType = EventType(358);
    pub const evNewFishingZoneObject: EventType = EventType(359);
    pub const evFishingMiniGame: EventType = EventType(360);
    pub const evAlbionJournalAchievementCompleted: EventType = EventType(361);
    pub const evUpdatePuppet: EventType = EventType(362);
    pub const evChangeFlaggingFinished: EventType = EventType(363);
    pub const evNewOutpostObject: EventType = EventType(364);
    pub const evOutpostUpdate: EventType = EventType(365);
    pub const evOutpostClaimed: EventType = EventType(366);
    pub const evOverChargeEnd: EventType = EventType(367);
    pub const evOverChargeStatus: EventType = EventType(368);
    pub const evPartyFinderFullUpdate: EventType = EventType(369);
    pub const evPartyFinderUpdate: EventType = EventType(370);
    pub const evPartyFinderApplicantsUpdate: EventType = EventType(371);
    pub const evPartyFinderEquipmentSnapshot: EventType = EventType(372);
    pub const evPartyFinderJoinRequestDeclined: EventType = EventType(373);
    pub const evNewUnlockedPersonalSeasonRewards: EventType = EventType(374);
    pub const evPersonalSeasonPointsGained: EventType = EventType(375);
    pub const evPersonalSeasonPastSeasonDataEvent: EventType = EventType(376);
    pub const evMatchLootChestOpeningStart: EventType = EventType(377);
    pub const evMatchLootChestOpeningFinished: EventType = EventType(378);
    pub const evMatchLootChestOpeningCancel: EventType = EventType(379);
    pub const evNotifyCrystalMatchReward: EventType = EventType(380);
    pub const evCrystalRealmFeedback: EventType = EventType(381);
    pub const evNewLocationMarker: EventType = EventType(382);
    pub const evNewTutorialBlocker: EventType = EventType(383);
    pub const evNewTileSwitch: EventType = EventType(384);
    pub const evNewInformationProvider: EventType = EventType(385);
    pub const evNewDynamicGuildLogo: EventType = EventType(386);
    pub const evNewDecoration: EventType = EventType(387);
    pub const evTutorialUpdate: EventType = EventType(388);
    pub const evTriggerHintBox: EventType = EventType(389);
    pub const evRandomDungeonPositionInfo: EventType = EventType(390);
    pub const evNewLootChest: EventType = EventType(391);
    pub const evUpdateLootChest: EventType = EventType(392);
    pub const evLootChestOpened: EventType = EventType(393);
    pub const evUpdateLootProtectedByMobsWithMinimapDisplay: EventType = EventType(394);
    pub const evNewShrine: EventType = EventType(395);
    pub const evUpdateShrine: EventType = EventType(396);
    pub const evUpdateRoom: EventType = EventType(397);
    pub const evNewMobSoul: EventType = EventType(398);
    pub const evNewHellgateShrine: EventType = EventType(399);
    pub const evUpdateHellgateShrine: EventType = EventType(400);
    pub const evActivateHellgateExit: EventType = EventType(401);
    pub const evMutePlayerUpdate: EventType = EventType(402);
    pub const evShopTileUpdate: EventType = EventType(403);
    pub const evShopUpdate: EventType = EventType(404);
    pub const evAntiCheatKick: EventType = EventType(405);
    pub const evBattlEyeServerMessage: EventType = EventType(406);
    pub const evUnlockVanityUnlock: EventType = EventType(407);
    pub const evAvatarUnlocked: EventType = EventType(408);
    pub const evCustomizationChanged: EventType = EventType(409);
    pub const evBaseVaultInfo: EventType = EventType(410);
    pub const evGuildVaultInfo: EventType = EventType(411);
    pub const evBankVaultInfo: EventType = EventType(412);
    pub const evRecoveryVaultPlayerInfo: EventType = EventType(413);
    pub const evRecoveryVaultGuildInfo: EventType = EventType(414);
    pub const evUpdateWardrobe: EventType = EventType(415);
    pub const evCastlePhaseChanged: EventType = EventType(416);
    pub const evGuildAccountLogEvent: EventType = EventType(417);
    pub const evNewHideoutObject: EventType = EventType(418);
    pub const evNewHideoutManagement: EventType = EventType(419);
    pub const evNewHideoutExit: EventType = EventType(420);
    pub const evInitHideoutAttackStart: EventType = EventType(421);
    pub const evInitHideoutAttackCancel: EventType = EventType(422);
    pub const evInitHideoutAttackFinished: EventType = EventType(423);
    pub const evHideoutManagementUpdate: EventType = EventType(424);
    pub const evHideoutUpgradeWithPowerCrystalResult: EventType = EventType(425);
    pub const evIpChanged: EventType = EventType(426);
    pub const evSmartClusterQueueUpdateInfo: EventType = EventType(427);
    pub const evSmartClusterQueueActiveInfo: EventType = EventType(428);
    pub const evSmartClusterQueueKickWarning: EventType = EventType(429);
    pub const evSmartClusterQueueInvite: EventType = EventType(430);
    pub const evReceivedGvgSeasonPoints: EventType = EventType(431);
    pub const evTowerPowerPointUpdate: EventType = EventType(432);
    pub const evOpenWorldAttackScheduleStart: EventType = EventType(433);
    pub const evOpenWorldAttackScheduleFinished: EventType = EventType(434);
    pub const evOpenWorldAttackScheduleCancel: EventType = EventType(435);
    pub const evOpenWorldAttackConquerStart: EventType = EventType(436);
    pub const evOpenWorldAttackConquerFinished: EventType = EventType(437);
    pub const evOpenWorldAttackConquerCancel: EventType = EventType(438);
    pub const evOpenWorldAttackConquerStatus: EventType = EventType(439);
    pub const evOpenWorldAttackStart: EventType = EventType(440);
    pub const evOpenWorldAttackEnd: EventType = EventType(441);
    pub const evNewRandomResourceBlocker: EventType = EventType(442);
    pub const evNewHomeObject: EventType = EventType(443);
    pub const evHideoutObjectUpdate: EventType = EventType(444);
    pub const evUpdateInfamy: EventType = EventType(445);
    pub const evMinimapPositionMarkers: EventType = EventType(446);
    pub const evNewTunnelExit: EventType = EventType(447);
    pub const evCorruptedDungeonUpdate: EventType = EventType(448);
    pub const evCorruptedDungeonStatus: EventType = EventType(449);
    pub const evCorruptedDungeonInfamy: EventType = EventType(450);
    pub const evHellgateRestrictedAreaUpdate: EventType = EventType(451);
    pub const evHellgateInfamy: EventType = EventType(452);
    pub const evHellgateStatus: EventType = EventType(453);
    pub const evHellgateStatusUpdate: EventType = EventType(454);
    pub const evHellgateSuspense: EventType = EventType(455);
    pub const evReplaceSpellSlotWithMultiSpell: EventType = EventType(456);
    pub const evNewCorruptedShrine: EventType = EventType(457);
    pub const evUpdateCorruptedShrine: EventType = EventType(458);
    pub const evCorruptedShrineUsageStart: EventType = EventType(459);
    pub const evCorruptedShrineUsageCancel: EventType = EventType(460);
    pub const evExitUsed: EventType = EventType(461);
    pub const evLinkedToObject: EventType = EventType(462);
    pub const evLinkToObjectBroken: EventType = EventType(463);
    pub const evEstimatedMarketValueUpdate: EventType = EventType(464);
    pub const evStuckCancel: EventType = EventType(465);
    pub const evDungonEscapeReady: EventType = EventType(466);
    pub const evFactionWarfareClusterState: EventType = EventType(467);
    pub const evFactionWarfareHasUnclaimedWeeklyReportsEvent: EventType = EventType(468);
    pub const evSimpleFeedback: EventType = EventType(469);
    pub const evSmartClusterQueueSkipClusterError: EventType = EventType(470);
    pub const evXignCodeEvent: EventType = EventType(471);
    pub const evBatchUseItemStart: EventType = EventType(472);
    pub const evBatchUseItemEnd: EventType = EventType(473);
    pub const evRedZonePlayerNotification: EventType = EventType(474);
    pub const evRedZoneEventCheatCleanup: EventType = EventType(475);
    pub const evRedZoneFortressEventChestOpened: EventType = EventType(476);
    pub const evRedZoneWorldMapEvent: EventType = EventType(477);
    pub const evFactionWarfareStats: EventType = EventType(478);
    pub const evUpdateFactionBalanceFactors: EventType = EventType(479);
    pub const evFactionEnlistmentChanged: EventType = EventType(480);
    pub const evUpdateFactionRank: EventType = EventType(481);
    pub const evFactionWarfareCampaignRewardsUnlocked: EventType = EventType(482);
    pub const evFeaturedFeatureUpdate: EventType = EventType(483);
    pub const evNewCarriableObject: EventType = EventType(484);
    pub const evMinimapCrystalPositionMarker: EventType = EventType(485);
    pub const evCarriedObjectUpdate: EventType = EventType(486);
    pub const evPickupCarriableObjectStart: EventType = EventType(487);
    pub const evPickupCarriableObjectCancel: EventType = EventType(488);
    pub const evPickupCarriableObjectFinished: EventType = EventType(489);
    pub const evDoSimpleActionStart: EventType = EventType(490);
    pub const evDoSimpleActionCancel: EventType = EventType(491);
    pub const evDoSimpleActionFinished: EventType = EventType(492);
    pub const evNotifyGuestAccountVerified: EventType = EventType(493);
    pub const evMightAndFavorReceivedEvent: EventType = EventType(494);
    pub const evWeeklyPvpChallengeRewardStateUpdate: EventType = EventType(495);
    pub const evNewUnlockedPvpSeasonChallengeRewards: EventType = EventType(496);
    pub const evStaticDungeonEntrancesDungeonEventStatusUpdates: EventType = EventType(497);
    pub const evStaticDungeonDungeonValueUpdate: EventType = EventType(498);
    pub const evStaticDungeonEntranceDungeonEventsAborted: EventType = EventType(499);
    pub const evInAppPurchaseConfirmedGooglePlay: EventType = EventType(500);
    pub const evFeatureSwitchInfo: EventType = EventType(501);
    pub const evPartyJoinRequestAborted: EventType = EventType(502);
    pub const evPartyInviteAborted: EventType = EventType(503);
    pub const evPartyStartHuntRequest: EventType = EventType(504);
    pub const evPartyStartHuntRequested: EventType = EventType(505);
    pub const evPartyStartHuntRequestAnswer: EventType = EventType(506);
    pub const evPartyPlayerLeaveScheduled: EventType = EventType(507);
    pub const evGuildInviteDeclined: EventType = EventType(508);
    pub const evCancelMultiSpellSlots: EventType = EventType(509);
    pub const evNewVisualEventObject: EventType = EventType(510);
    pub const evCastleClaimProgress: EventType = EventType(511);
    pub const evCastleClaimProgressLogo: EventType = EventType(512);
    pub const evTownPortalUpdateState: EventType = EventType(513);
    pub const evTownPortalFailed: EventType = EventType(514);
    pub const evConsumableVanityChargesAdded: EventType = EventType(515);
    pub const evFestivitiesUpdate: EventType = EventType(516);
    pub const evNewBannerObject: EventType = EventType(517);
    pub const evNewMistsImmediateReturnExit: EventType = EventType(518);
    pub const evMistsPlayerJoinedInfo: EventType = EventType(519);
    pub const evNewMistsStaticEntrance: EventType = EventType(520);
    pub const evNewMistsOpenWorldExit: EventType = EventType(521);
    pub const evNewTunnelExitTemp: EventType = EventType(522);
    pub const evNewMistsWispSpawn: EventType = EventType(523);
    pub const evMistsWispSpawnStateChange: EventType = EventType(524);
    pub const evNewMistsCityEntrance: EventType = EventType(525);
    pub const evNewMistsCityRoadsEntrance: EventType = EventType(526);
    pub const evMistsCityRoadsEntrancePartyStateUpdate: EventType = EventType(527);
    pub const evMistsCityRoadsEntranceClearStateForParty: EventType = EventType(528);
    pub const evMistsEntranceDataChanged: EventType = EventType(529);
    pub const evNewCagedObject: EventType = EventType(530);
    pub const evCagedObjectStateUpdated: EventType = EventType(531);
    pub const evEntrancePartyBindingCreated: EventType = EventType(532);
    pub const evEntrancePartyBindingCleared: EventType = EventType(533);
    pub const evEntrancePartyBindingInfos: EventType = EventType(534);
    pub const evNewMistsBorderExit: EventType = EventType(535);
    pub const evNewMistsDungeonExit: EventType = EventType(536);
    pub const evLocalQuestInfos: EventType = EventType(537);
    pub const evLocalQuestStarted: EventType = EventType(538);
    pub const evLocalQuestActive: EventType = EventType(539);
    pub const evLocalQuestInactive: EventType = EventType(540);
    pub const evLocalQuestProgressUpdate: EventType = EventType(541);
    pub const evNewUnrestrictedPvpZone: EventType = EventType(542);
    pub const evTemporaryFlaggingStatusUpdate: EventType = EventType(543);
    pub const evSpellTestPerformanceUpdate: EventType = EventType(544);
    pub const evTransformation: EventType = EventType(545);
    pub const evTransformationEnd: EventType = EventType(546);
    pub const evUpdateTrustlevel: EventType = EventType(547);
    pub const evRevealHiddenTimeStamps: EventType = EventType(548);
    pub const evModifyItemTraitFinished: EventType = EventType(549);
    pub const evRerollItemTraitValueFinished: EventType = EventType(550);
    pub const evHuntQuestProgressInfo: EventType = EventType(551);
    pub const evHuntStarted: EventType = EventType(552);
    pub const evHuntFinished: EventType = EventType(553);
    pub const evHuntAborted: EventType = EventType(554);
    pub const evHuntMissionStepStateUpdate: EventType = EventType(555);
    pub const evNewHuntTrack: EventType = EventType(556);
    pub const evHuntMissionUpdate: EventType = EventType(557);
    pub const evHuntQuestMissionProgressUpdate: EventType = EventType(558);
    pub const evHuntTrackUsed: EventType = EventType(559);
    pub const evHuntTrackUseableAgain: EventType = EventType(560);
    pub const evMinimapHuntTrackMarkers: EventType = EventType(561);
    pub const evNoTracksFound: EventType = EventType(562);
    pub const evHuntQuestAborted: EventType = EventType(563);
    pub const evInteractWithTrackStart: EventType = EventType(564);
    pub const evInteractWithTrackCancel: EventType = EventType(565);
    pub const evInteractWithTrackFinished: EventType = EventType(566);
    pub const evNewDynamicCompound: EventType = EventType(567);
    pub const evLegendaryItemDestroyed: EventType = EventType(568);
    pub const evAttunementInfo: EventType = EventType(569);
    pub const evTerritoryClaimRaidedRawEnergyCrystalResult: EventType = EventType(570);
    pub const evCarriedObjectExpiryWarning: EventType = EventType(571);
    pub const evCarriedObjectExpired: EventType = EventType(572);
    pub const evTerritoryRaidStart: EventType = EventType(573);
    pub const evTerritoryRaidCancel: EventType = EventType(574);
    pub const evTerritoryRaidFinished: EventType = EventType(575);
    pub const evTerritoryRaidResult: EventType = EventType(576);
    pub const evTerritoryMonolithActiveRaidStatus: EventType = EventType(577);
    pub const evTerritoryMonolithActiveRaidCancelled: EventType = EventType(578);
    pub const evMonolithEnergyStorageUpdate: EventType = EventType(579);
    pub const evMonolithNextScheduledOpenWorldAttackUpdate: EventType = EventType(580);
    pub const evMonolithProtectedBuildingsDamageReductionUpdate: EventType = EventType(581);
    pub const evNewBuildingBaseEvent: EventType = EventType(582);
    pub const evNewFortificationBuilding: EventType = EventType(583);
    pub const evNewCastleGateBuilding: EventType = EventType(584);
    pub const evBuildingDurabilityUpdate: EventType = EventType(585);
    pub const evMonolithFortificationPointsUpdate: EventType = EventType(586);
    pub const evFortificationBuildingUpgradeInfo: EventType = EventType(587);
    pub const evFortificationBuildingsDamageStateUpdate: EventType = EventType(588);
    pub const evSiegeNotificationEvent: EventType = EventType(589);
    pub const evUpdateEnemyWarBannerActive: EventType = EventType(590);
    pub const evTerritoryAnnouncePlayerEjection: EventType = EventType(591);
    pub const evCastleGateSwitchUseStarted: EventType = EventType(592);
    pub const evCastleGateSwitchUseFinished: EventType = EventType(593);
    pub const evFortificationBuildingWillDowngrade: EventType = EventType(594);
    pub const evBotCommand: EventType = EventType(595);
    pub const evJournalAchievementProgressUpdate: EventType = EventType(596);
    pub const evJournalClaimableRewardUpdate: EventType = EventType(597);
    pub const evKeySync: EventType = EventType(598);
    pub const evLocalQuestAreaGone: EventType = EventType(599);
    pub const evDynamicTemplate: EventType = EventType(600);
    pub const evDynamicTemplateForcedStateChange: EventType = EventType(601);
    pub const evNewOutlandsTeleportationPortal: EventType = EventType(602);
    pub const evNewOutlandsTeleportationReturnPortal: EventType = EventType(603);
    pub const evOutlandsTeleportationBindingCleared: EventType = EventType(604);
    pub const evOutlandsTeleportationReturnPortalUpdateEvent: EventType = EventType(605);
    pub const evPlayerUsedOutlandsTeleportationPortal: EventType = EventType(606);
    pub const evEncumberedRestricted: EventType = EventType(607);
    pub const evNewPiledObject: EventType = EventType(608);
    pub const evPiledObjectStateChanged: EventType = EventType(609);
    pub const evNewSmugglerCrateDeliveryStation: EventType = EventType(610);
    pub const evKillRewardedNoFame: EventType = EventType(611);
    pub const evPickupFromPiledObjectStart: EventType = EventType(612);
    pub const evPickupFromPiledObjectCancel: EventType = EventType(613);
    pub const evPickupFromPiledObjectReset: EventType = EventType(614);
    pub const evPickupFromPiledObjectFinished: EventType = EventType(615);
    pub const evArmoryActivityChange: EventType = EventType(616);
    pub const evNewKillTrophyFurnitureBuilding: EventType = EventType(617);
    pub const evHellDungeonsPlayerJoinedInfo: EventType = EventType(618);
    pub const evNewTileSwitchTrigger: EventType = EventType(619);
    pub const evNewMultiRewardObject: EventType = EventType(620);
    pub const evNewHellDungeonSoulShrineObject: EventType = EventType(621);
    pub const evHellDungeonSoulShrineStateUpdate: EventType = EventType(622);
    pub const evNewResurrectionShrine: EventType = EventType(623);
    pub const evUpdateResurrectionShrine: EventType = EventType(624);
    pub const evStandTimeFinished: EventType = EventType(625);
    pub const evEpicAchievementAndStatsUpdate: EventType = EventType(626);
    pub const evSpectateTargetAfterDeathUpdate: EventType = EventType(627);
    pub const evSpectateTargetAfterDeathEnded: EventType = EventType(628);
    pub const evNewHellDungeonUpwardExit: EventType = EventType(629);
    pub const evNewHellDungeonSoulExit: EventType = EventType(630);
    pub const evNewHellDungeonDownwardExit: EventType = EventType(631);
    pub const evNewHellDungeonChestExit: EventType = EventType(632);
    pub const evNewCorruptedStaticEntrance: EventType = EventType(633);
    pub const evNewHellDungeonStaticEntrance: EventType = EventType(634);
    pub const evUpdateHellDungeonStaticEntranceState: EventType = EventType(635);
    pub const evDebugTriggerHellDungeonShutdownStart: EventType = EventType(636);
    pub const evFullJournalQuestInfo: EventType = EventType(637);
    pub const evJournalQuestProgressInfo: EventType = EventType(638);
    pub const evNewHellDungeonRoomShrineObject: EventType = EventType(639);
    pub const evHellDungeonRoomShrineStateUpdate: EventType = EventType(640);
    pub const evSimpleBehaviourBuildingStateUpdate: EventType = EventType(641);
    pub const evSetTimeScaling: EventType = EventType(642);
    pub const evStopTimeScaling: EventType = EventType(643);
    pub const evKeyValidation: EventType = EventType(644);
    pub const evPlayerJoinMapMarkerTimerStates: EventType = EventType(645);
    pub const evNewMapMarkerTimer: EventType = EventType(646);
    pub const evRemoveMapMarkerTimer: EventType = EventType(647);
    pub const evNewFactionFortressObject: EventType = EventType(648);
    pub const evFactionFortressAnnouncePlayerEjection: EventType = EventType(649);
    pub const evRewardFactionWarfareSupply: EventType = EventType(650);
    pub const evFactionCaptureAreaProgressUpdate: EventType = EventType(651);
    pub const evFactionFortressClaimed: EventType = EventType(652);
    pub const evFactionFortressWeaponCachesSpawned: EventType = EventType(653);
    pub const evFactionFortressWeaponCacheClaimed: EventType = EventType(654);
    pub const evFactionFortressFightStateUpdate: EventType = EventType(655);
    pub const evFactionFortressCutoffFightStateUpdate: EventType = EventType(656);
    pub const evFactionFortressFightEnded: EventType = EventType(657);
    pub const evNewFactionWarfarePortal: EventType = EventType(658);
    pub const evFactionPortalTargetUpdate: EventType = EventType(659);
    pub const evFactionFortressFightStartedInRemoteClusterEvent: EventType = EventType(660);
    pub const evFactionFortressFightFinishedInRemoteClusterEvent: EventType = EventType(661);
    pub const evFactionDuchySupplyWarDefensiveVictoryEvent: EventType = EventType(662);
    pub const evFactionDuchyReconnectedFromCutoffEvent: EventType = EventType(663);
    pub const evFactionFortressCutoffFightCancelledByClusterOwnerChangeEvent: EventType =
        EventType(664);
    pub const evFactionDuchyEnteredCutoffStateEvent: EventType = EventType(665);
    pub const evLeaveProtectionStateUpdate: EventType = EventType(666);
    pub const evRedZoneEventStandings: EventType = EventType(667);
    pub const evNewFactionBattleStandardDeliveryStation: EventType = EventType(668);
    pub const evNewLoreSnippetObject: EventType = EventType(669);
    pub const evLoreSnippetObjectStateUpdate: EventType = EventType(670);
    pub const evLoreSnippedClaimed: EventType = EventType(671);
    pub const evLoreSnippetStatesChangedByCheat: EventType = EventType(672);
    pub const evNewTeleporterNode: EventType = EventType(673);
    pub const evTeleporterNodeStateChanged: EventType = EventType(674);
    pub const evTeleporterConnectionsFullStateUpdate: EventType = EventType(675);
    pub const evTeleporterConnectionStateChanged: EventType = EventType(676);
    pub const evRetrieveCarriableObjectStart: EventType = EventType(677);
    pub const evRetrieveCarriableObjectCancel: EventType = EventType(678);
    pub const evRetrieveCarriableObjectReset: EventType = EventType(679);
    pub const evRetrieveCarriableObjectFinished: EventType = EventType(680);
    pub const evLosingCarriableObjectStart: EventType = EventType(681);
    pub const evLosingCarriableObjectFinished: EventType = EventType(682);
}

impl std::fmt::Display for EventType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let name = match self.0 {
            0 => "evUnused",
            1 => "evLeave",
            2 => "evJoinFinished",
            3 => "evMove",
            4 => "evTeleport",
            5 => "evChangeEquipment",
            6 => "evHealthUpdate",
            7 => "evHealthUpdates",
            8 => "evEnergyUpdate",
            9 => "evDamageShieldUpdate",
            10 => "evCraftingFocusUpdate",
            11 => "evActiveSpellEffectsUpdate",
            12 => "evResetCooldowns",
            13 => "evAttack",
            14 => "evCastStart",
            15 => "evChannelingUpdate",
            16 => "evCastCancel",
            17 => "evCastTimeUpdate",
            18 => "evCastFinished",
            19 => "evCastSpell",
            20 => "evCastSpells",
            21 => "evCastHit",
            22 => "evCastHits",
            23 => "evStoredTargetsUpdate",
            24 => "evChannelingEnded",
            25 => "evAttackBuilding",
            26 => "evInventoryPutItem",
            27 => "evInventoryDeleteItem",
            28 => "evInventoryState",
            29 => "evNewCharacter",
            30 => "evNewEquipmentItem",
            31 => "evNewSiegeBannerItem",
            32 => "evNewSimpleItem",
            33 => "evNewFurnitureItem",
            34 => "evNewKillTrophyItem",
            35 => "evNewJournalItem",
            36 => "evNewLaborerItem",
            37 => "evNewEquipmentItemLegendarySoul",
            38 => "evNewSimpleHarvestableObject",
            39 => "evNewSimpleHarvestableObjectList",
            40 => "evNewHarvestableObject",
            41 => "evNewTreasureDestinationObject",
            42 => "evTreasureDestinationObjectStatus",
            43 => "evCloseTreasureDestinationObject",
            44 => "evNewSilverObject",
            45 => "evNewBuilding",
            46 => "evHarvestableChangeState",
            47 => "evMobChangeState",
            48 => "evFactionBuildingInfo",
            49 => "evCraftBuildingInfo",
            50 => "evRepairBuildingInfo",
            51 => "evMeldBuildingInfo",
            52 => "evConstructionSiteInfo",
            53 => "evPlayerBuildingInfo",
            54 => "evFarmBuildingInfo",
            55 => "evTutorialBuildingInfo",
            56 => "evLaborerObjectInfo",
            57 => "evLaborerObjectJobInfo",
            58 => "evMarketPlaceBuildingInfo",
            59 => "evHarvestStart",
            60 => "evHarvestCancel",
            61 => "evHarvestFinished",
            62 => "evTakeSilver",
            63 => "evRemoveSilver",
            64 => "evActionOnBuildingStart",
            65 => "evActionOnBuildingCancel",
            66 => "evActionOnBuildingFinished",
            67 => "evItemRerollQualityFinished",
            68 => "evInstallResourceStart",
            69 => "evInstallResourceCancel",
            70 => "evInstallResourceFinished",
            71 => "evCraftItemFinished",
            72 => "evLogoutCancel",
            73 => "evChatMessage",
            74 => "evChatSay",
            75 => "evChatWhisper",
            76 => "evChatMuted",
            77 => "evPlayEmote",
            78 => "evStopEmote",
            79 => "evSystemMessage",
            80 => "evUtilityTextMessage",
            81 => "evUpdateMoney",
            82 => "evUpdateFame",
            83 => "evUpdateLearningPoints",
            84 => "evUpdateReSpecPoints",
            85 => "evUpdateCurrency",
            86 => "evUpdateFactionStanding",
            87 => "evUpdateStanding",
            88 => "evRespawn",
            89 => "evServerDebugLog",
            90 => "evCharacterEquipmentChanged",
            91 => "evRegenerationHealthChanged",
            92 => "evRegenerationEnergyChanged",
            93 => "evRegenerationMountHealthChanged",
            94 => "evRegenerationCraftingChanged",
            95 => "evRegenerationHealthEnergyComboChanged",
            96 => "evRegenerationPlayerComboChanged",
            97 => "evDurabilityChanged",
            98 => "evNewLoot",
            99 => "evAttachItemContainer",
            100 => "evDetachItemContainer",
            101 => "evInvalidateItemContainer",
            102 => "evLockItemContainer",
            103 => "evGuildUpdate",
            104 => "evGuildPlayerUpdated",
            105 => "evInvitedToGuild",
            106 => "evGuildMemberWorldUpdate",
            107 => "evUpdateMatchDetails",
            108 => "evObjectEvent",
            109 => "evNewMonolithObject",
            110 => "evMonolithHasBannersPlacedUpdate",
            111 => "evNewOrbObject",
            112 => "evNewCastleObject",
            113 => "evNewSpellEffectArea",
            114 => "evUpdateSpellEffectArea",
            115 => "evNewChainSpell",
            116 => "evUpdateChainSpell",
            117 => "evNewTreasureChest",
            118 => "evStartMatch",
            119 => "evStartArenaMatchInfos",
            120 => "evEndArenaMatch",
            121 => "evMatchUpdate",
            122 => "evActiveMatchUpdate",
            123 => "evNewMob",
            124 => "evDebugMobInfo",
            125 => "evDebugVariablesInfo",
            126 => "evDebugReputationInfo",
            127 => "evDebugDiminishingReturnInfo",
            128 => "evDebugSmartClusterQueueInfo",
            129 => "evClaimOrbStart",
            130 => "evClaimOrbFinished",
            131 => "evClaimOrbCancel",
            132 => "evOrbUpdate",
            133 => "evOrbClaimed",
            134 => "evOrbReset",
            135 => "evNewWarCampObject",
            136 => "evNewMatchLootChestObject",
            137 => "evNewArenaExit",
            138 => "evGuildMemberTerritoryUpdate",
            139 => "evInvitedMercenaryToMatch",
            140 => "evClusterInfoUpdate",
            141 => "evForcedMovement",
            142 => "evForcedMovementCancel",
            143 => "evCharacterStats",
            144 => "evCharacterStatsKillHistory",
            145 => "evCharacterStatsDeathHistory",
            146 => "evCharacterStatsKnockDownHistory",
            147 => "evCharacterStatsKnockedDownHistory",
            148 => "evGuildStats",
            149 => "evKillHistoryDetails",
            150 => "evItemKillHistoryDetails",
            151 => "evFullAchievementInfo",
            152 => "evFinishedAchievement",
            153 => "evAchievementProgressInfo",
            154 => "evFullAchievementProgressInfo",
            155 => "evFullTrackedAchievementInfo",
            156 => "evFullAutoLearnAchievementInfo",
            157 => "evQuestGiverQuestOffered",
            158 => "evQuestGiverDebugInfo",
            159 => "evConsoleEvent",
            160 => "evTimeSync",
            161 => "evChangeAvatar",
            162 => "evChangeMountSkin",
            163 => "evGameEvent",
            164 => "evKilledPlayer",
            165 => "evDied",
            166 => "evKnockedDown",
            167 => "evUnconcious",
            168 => "evMatchPlayerJoinedEvent",
            169 => "evMatchPlayerStatsEvent",
            170 => "evMatchPlayerStatsCompleteEvent",
            171 => "evMatchTimeLineEventEvent",
            172 => "evMatchNewCombatRound",
            173 => "evMatchEndCombatRound",
            174 => "evMatchPlayerMainGearStatsEvent",
            175 => "evMatchPlayerChangedAvatarEvent",
            176 => "evInvitationPlayerTrade",
            177 => "evPlayerTradeStart",
            178 => "evPlayerTradeCancel",
            179 => "evPlayerTradeUpdate",
            180 => "evPlayerTradeFinished",
            181 => "evPlayerTradeAcceptChange",
            182 => "evMiniMapPing",
            183 => "evMarketPlaceNotification",
            184 => "evDuellingChallengePlayer",
            185 => "evNewDuellingPost",
            186 => "evDuelStarted",
            187 => "evDuelEnded",
            188 => "evDuelDenied",
            189 => "evDuelRequestCanceled",
            190 => "evDuelLeftArea",
            191 => "evDuelReEnteredArea",
            192 => "evNewRealEstate",
            193 => "evMiniMapOwnedBuildingsPositions",
            194 => "evRealEstateListUpdate",
            195 => "evGuildLogoUpdate",
            196 => "evGuildLogoChanged",
            197 => "evPlaceableObjectPlace",
            198 => "evPlaceableObjectPlaceCancel",
            199 => "evFurnitureObjectBuffProviderInfo",
            200 => "evFurnitureObjectCheatProviderInfo",
            201 => "evFarmableObjectInfo",
            202 => "evNewUnreadMails",
            203 => "evMailOperationPossible",
            204 => "evGuildLogoObjectUpdate",
            205 => "evStartLogout",
            206 => "evNewChatChannels",
            207 => "evJoinedChatChannel",
            208 => "evLeftChatChannel",
            209 => "evRemovedChatChannel",
            210 => "evAccessStatus",
            211 => "evMounted",
            212 => "evMountStart",
            213 => "evMountCancel",
            214 => "evNewTravelpoint",
            215 => "evNewIslandAccessPoint",
            216 => "evNewExit",
            217 => "evUpdateHome",
            218 => "evUpdateChatSettings",
            219 => "evResurrectionOffer",
            220 => "evResurrectionReply",
            221 => "evLootEquipmentChanged",
            222 => "evUpdateUnlockedGuildLogos",
            223 => "evUpdateUnlockedAvatars",
            224 => "evUpdateUnlockedAvatarRings",
            225 => "evUpdateUnlockedBuildings",
            226 => "evNewIslandManagement",
            227 => "evNewTeleportStone",
            228 => "evCloak",
            229 => "evPartyInvitation",
            230 => "evPartyJoinRequest",
            231 => "evPartyJoined",
            232 => "evPartyDisbanded",
            233 => "evPartyPlayerJoined",
            234 => "evPartyChangedOrder",
            235 => "evPartyPlayerLeft",
            236 => "evPartyLeaderChanged",
            237 => "evPartyLootSettingChangedPlayer",
            238 => "evPartySilverGained",
            239 => "evPartyPlayerUpdated",
            240 => "evPartyInvitationAnswer",
            241 => "evPartyJoinRequestAnswer",
            242 => "evPartyMarkedObjectsUpdated",
            243 => "evPartyOnClusterPartyJoined",
            244 => "evPartySetRoleFlag",
            245 => "evPartyInviteOrJoinPlayerEquipmentInfo",
            246 => "evPartyReadyCheckUpdate",
            247 => "evPartyFactionWarfareReinforcementSettingChangedPlayer",
            248 => "evSpellCooldownUpdate",
            249 => "evNewHellgateExitPortal",
            250 => "evNewExpeditionExit",
            251 => "evNewExpeditionNarrator",
            252 => "evExitEnterStart",
            253 => "evExitEnterCancel",
            254 => "evExitEnterFinished",
            255 => "evNewQuestGiverObject",
            256 => "evFullQuestInfo",
            257 => "evQuestProgressInfo",
            258 => "evQuestGiverInfoForPlayer",
            259 => "evFullExpeditionInfo",
            260 => "evExpeditionQuestProgressInfo",
            261 => "evInvitedToExpedition",
            262 => "evExpeditionRegistrationInfo",
            263 => "evEnteringExpeditionStart",
            264 => "evEnteringExpeditionCancel",
            265 => "evRewardGranted",
            266 => "evArenaRegistrationInfo",
            267 => "evEnteringArenaStart",
            268 => "evEnteringArenaCancel",
            269 => "evEnteringArenaLockStart",
            270 => "evEnteringArenaLockCancel",
            271 => "evInvitedToArenaMatch",
            272 => "evUsingHellgateShrine",
            273 => "evEnteringHellgateLockStart",
            274 => "evEnteringHellgateLockCancel",
            275 => "evPlayerCounts",
            276 => "evInCombatStateUpdate",
            277 => "evOtherGrabbedLoot",
            278 => "evTreasureChestUsingStart",
            279 => "evTreasureChestUsingFinished",
            280 => "evTreasureChestUsingCancel",
            281 => "evTreasureChestUsingOpeningComplete",
            282 => "evTreasureChestForceCloseInventory",
            283 => "evLocalTreasuresUpdate",
            284 => "evLootChestSpawnpointsUpdate",
            285 => "evPremiumChanged",
            286 => "evPremiumExtended",
            287 => "evPremiumLifeTimeRewardGained",
            288 => "evGoldPurchased",
            289 => "evLaborerGotUpgraded",
            290 => "evJournalGotFull",
            291 => "evJournalFillError",
            292 => "evFriendRequest",
            293 => "evFriendRequestInfos",
            294 => "evFriendInfos",
            295 => "evFriendRequestAnswered",
            296 => "evFriendOnlineStatus",
            297 => "evFriendRequestCanceled",
            298 => "evFriendRemoved",
            299 => "evFriendUpdated",
            300 => "evPartyLootItems",
            301 => "evPartyLootItemsRemoved",
            302 => "evPartyLootItemTypesRemoved",
            303 => "evReputationUpdate",
            304 => "evDefenseUnitAttackBegin",
            305 => "evDefenseUnitAttackEnd",
            306 => "evDefenseUnitAttackDamage",
            307 => "evUnrestrictedPvpZoneUpdate",
            308 => "evUnrestrictedPvpZoneStatus",
            309 => "evReputationImplicationUpdate",
            310 => "evNewMountObject",
            311 => "evMountHealthUpdate",
            312 => "evMountCooldownUpdate",
            313 => "evNewExpeditionAgent",
            314 => "evNewExpeditionCheckPoint",
            315 => "evExpeditionStartEvent",
            316 => "evVoteEvent",
            317 => "evRatingEvent",
            318 => "evNewArenaAgent",
            319 => "evBoostFarmable",
            320 => "evUseFunction",
            321 => "evNewPortalEntrance",
            322 => "evNewPortalExit",
            323 => "evNewRandomDungeonExit",
            324 => "evWaitingQueueUpdate",
            325 => "evPlayerMovementRateUpdate",
            326 => "evObserveStart",
            327 => "evMinimapZergs",
            328 => "evMinimapSmartClusterZergs",
            329 => "evPaymentTransactions",
            330 => "evPerformanceStatsUpdate",
            331 => "evOverloadModeUpdate",
            332 => "evDebugDrawEvent",
            333 => "evRecordCameraMove",
            334 => "evRecordStart",
            335 => "evDeliverCarriableObjectStart",
            336 => "evDeliverCarriableObjectCancel",
            337 => "evDeliverCarriableObjectReset",
            338 => "evDeliverCarriableObjectFinished",
            339 => "evTerritoryClaimStart",
            340 => "evTerritoryClaimCancel",
            341 => "evTerritoryClaimFinished",
            342 => "evTerritoryScheduleResult",
            343 => "evTerritoryUpgradeWithPowerCrystalResult",
            344 => "evReceiveCarriableObjectStart",
            345 => "evReceiveCarriableObjectFinished",
            346 => "evUpdateAccountState",
            347 => "evStartDeterministicRoam",
            348 => "evGuildFullAccessTagsUpdated",
            349 => "evGuildAccessTagUpdated",
            350 => "evGvgSeasonUpdate",
            351 => "evGvgSeasonCheatCommand",
            352 => "evSeasonPointsByKillingBooster",
            353 => "evFishingStart",
            354 => "evFishingCast",
            355 => "evFishingCatch",
            356 => "evFishingFinished",
            357 => "evFishingCancel",
            358 => "evNewFloatObject",
            359 => "evNewFishingZoneObject",
            360 => "evFishingMiniGame",
            361 => "evAlbionJournalAchievementCompleted",
            362 => "evUpdatePuppet",
            363 => "evChangeFlaggingFinished",
            364 => "evNewOutpostObject",
            365 => "evOutpostUpdate",
            366 => "evOutpostClaimed",
            367 => "evOverChargeEnd",
            368 => "evOverChargeStatus",
            369 => "evPartyFinderFullUpdate",
            370 => "evPartyFinderUpdate",
            371 => "evPartyFinderApplicantsUpdate",
            372 => "evPartyFinderEquipmentSnapshot",
            373 => "evPartyFinderJoinRequestDeclined",
            374 => "evNewUnlockedPersonalSeasonRewards",
            375 => "evPersonalSeasonPointsGained",
            376 => "evPersonalSeasonPastSeasonDataEvent",
            377 => "evMatchLootChestOpeningStart",
            378 => "evMatchLootChestOpeningFinished",
            379 => "evMatchLootChestOpeningCancel",
            380 => "evNotifyCrystalMatchReward",
            381 => "evCrystalRealmFeedback",
            382 => "evNewLocationMarker",
            383 => "evNewTutorialBlocker",
            384 => "evNewTileSwitch",
            385 => "evNewInformationProvider",
            386 => "evNewDynamicGuildLogo",
            387 => "evNewDecoration",
            388 => "evTutorialUpdate",
            389 => "evTriggerHintBox",
            390 => "evRandomDungeonPositionInfo",
            391 => "evNewLootChest",
            392 => "evUpdateLootChest",
            393 => "evLootChestOpened",
            394 => "evUpdateLootProtectedByMobsWithMinimapDisplay",
            395 => "evNewShrine",
            396 => "evUpdateShrine",
            397 => "evUpdateRoom",
            398 => "evNewMobSoul",
            399 => "evNewHellgateShrine",
            400 => "evUpdateHellgateShrine",
            401 => "evActivateHellgateExit",
            402 => "evMutePlayerUpdate",
            403 => "evShopTileUpdate",
            404 => "evShopUpdate",
            405 => "evAntiCheatKick",
            406 => "evBattlEyeServerMessage",
            407 => "evUnlockVanityUnlock",
            408 => "evAvatarUnlocked",
            409 => "evCustomizationChanged",
            410 => "evBaseVaultInfo",
            411 => "evGuildVaultInfo",
            412 => "evBankVaultInfo",
            413 => "evRecoveryVaultPlayerInfo",
            414 => "evRecoveryVaultGuildInfo",
            415 => "evUpdateWardrobe",
            416 => "evCastlePhaseChanged",
            417 => "evGuildAccountLogEvent",
            418 => "evNewHideoutObject",
            419 => "evNewHideoutManagement",
            420 => "evNewHideoutExit",
            421 => "evInitHideoutAttackStart",
            422 => "evInitHideoutAttackCancel",
            423 => "evInitHideoutAttackFinished",
            424 => "evHideoutManagementUpdate",
            425 => "evHideoutUpgradeWithPowerCrystalResult",
            426 => "evIpChanged",
            427 => "evSmartClusterQueueUpdateInfo",
            428 => "evSmartClusterQueueActiveInfo",
            429 => "evSmartClusterQueueKickWarning",
            430 => "evSmartClusterQueueInvite",
            431 => "evReceivedGvgSeasonPoints",
            432 => "evTowerPowerPointUpdate",
            433 => "evOpenWorldAttackScheduleStart",
            434 => "evOpenWorldAttackScheduleFinished",
            435 => "evOpenWorldAttackScheduleCancel",
            436 => "evOpenWorldAttackConquerStart",
            437 => "evOpenWorldAttackConquerFinished",
            438 => "evOpenWorldAttackConquerCancel",
            439 => "evOpenWorldAttackConquerStatus",
            440 => "evOpenWorldAttackStart",
            441 => "evOpenWorldAttackEnd",
            442 => "evNewRandomResourceBlocker",
            443 => "evNewHomeObject",
            444 => "evHideoutObjectUpdate",
            445 => "evUpdateInfamy",
            446 => "evMinimapPositionMarkers",
            447 => "evNewTunnelExit",
            448 => "evCorruptedDungeonUpdate",
            449 => "evCorruptedDungeonStatus",
            450 => "evCorruptedDungeonInfamy",
            451 => "evHellgateRestrictedAreaUpdate",
            452 => "evHellgateInfamy",
            453 => "evHellgateStatus",
            454 => "evHellgateStatusUpdate",
            455 => "evHellgateSuspense",
            456 => "evReplaceSpellSlotWithMultiSpell",
            457 => "evNewCorruptedShrine",
            458 => "evUpdateCorruptedShrine",
            459 => "evCorruptedShrineUsageStart",
            460 => "evCorruptedShrineUsageCancel",
            461 => "evExitUsed",
            462 => "evLinkedToObject",
            463 => "evLinkToObjectBroken",
            464 => "evEstimatedMarketValueUpdate",
            465 => "evStuckCancel",
            466 => "evDungonEscapeReady",
            467 => "evFactionWarfareClusterState",
            468 => "evFactionWarfareHasUnclaimedWeeklyReportsEvent",
            469 => "evSimpleFeedback",
            470 => "evSmartClusterQueueSkipClusterError",
            471 => "evXignCodeEvent",
            472 => "evBatchUseItemStart",
            473 => "evBatchUseItemEnd",
            474 => "evRedZonePlayerNotification",
            475 => "evRedZoneEventCheatCleanup",
            476 => "evRedZoneFortressEventChestOpened",
            477 => "evRedZoneWorldMapEvent",
            478 => "evFactionWarfareStats",
            479 => "evUpdateFactionBalanceFactors",
            480 => "evFactionEnlistmentChanged",
            481 => "evUpdateFactionRank",
            482 => "evFactionWarfareCampaignRewardsUnlocked",
            483 => "evFeaturedFeatureUpdate",
            484 => "evNewCarriableObject",
            485 => "evMinimapCrystalPositionMarker",
            486 => "evCarriedObjectUpdate",
            487 => "evPickupCarriableObjectStart",
            488 => "evPickupCarriableObjectCancel",
            489 => "evPickupCarriableObjectFinished",
            490 => "evDoSimpleActionStart",
            491 => "evDoSimpleActionCancel",
            492 => "evDoSimpleActionFinished",
            493 => "evNotifyGuestAccountVerified",
            494 => "evMightAndFavorReceivedEvent",
            495 => "evWeeklyPvpChallengeRewardStateUpdate",
            496 => "evNewUnlockedPvpSeasonChallengeRewards",
            497 => "evStaticDungeonEntrancesDungeonEventStatusUpdates",
            498 => "evStaticDungeonDungeonValueUpdate",
            499 => "evStaticDungeonEntranceDungeonEventsAborted",
            500 => "evInAppPurchaseConfirmedGooglePlay",
            501 => "evFeatureSwitchInfo",
            502 => "evPartyJoinRequestAborted",
            503 => "evPartyInviteAborted",
            504 => "evPartyStartHuntRequest",
            505 => "evPartyStartHuntRequested",
            506 => "evPartyStartHuntRequestAnswer",
            507 => "evPartyPlayerLeaveScheduled",
            508 => "evGuildInviteDeclined",
            509 => "evCancelMultiSpellSlots",
            510 => "evNewVisualEventObject",
            511 => "evCastleClaimProgress",
            512 => "evCastleClaimProgressLogo",
            513 => "evTownPortalUpdateState",
            514 => "evTownPortalFailed",
            515 => "evConsumableVanityChargesAdded",
            516 => "evFestivitiesUpdate",
            517 => "evNewBannerObject",
            518 => "evNewMistsImmediateReturnExit",
            519 => "evMistsPlayerJoinedInfo",
            520 => "evNewMistsStaticEntrance",
            521 => "evNewMistsOpenWorldExit",
            522 => "evNewTunnelExitTemp",
            523 => "evNewMistsWispSpawn",
            524 => "evMistsWispSpawnStateChange",
            525 => "evNewMistsCityEntrance",
            526 => "evNewMistsCityRoadsEntrance",
            527 => "evMistsCityRoadsEntrancePartyStateUpdate",
            528 => "evMistsCityRoadsEntranceClearStateForParty",
            529 => "evMistsEntranceDataChanged",
            530 => "evNewCagedObject",
            531 => "evCagedObjectStateUpdated",
            532 => "evEntrancePartyBindingCreated",
            533 => "evEntrancePartyBindingCleared",
            534 => "evEntrancePartyBindingInfos",
            535 => "evNewMistsBorderExit",
            536 => "evNewMistsDungeonExit",
            537 => "evLocalQuestInfos",
            538 => "evLocalQuestStarted",
            539 => "evLocalQuestActive",
            540 => "evLocalQuestInactive",
            541 => "evLocalQuestProgressUpdate",
            542 => "evNewUnrestrictedPvpZone",
            543 => "evTemporaryFlaggingStatusUpdate",
            544 => "evSpellTestPerformanceUpdate",
            545 => "evTransformation",
            546 => "evTransformationEnd",
            547 => "evUpdateTrustlevel",
            548 => "evRevealHiddenTimeStamps",
            549 => "evModifyItemTraitFinished",
            550 => "evRerollItemTraitValueFinished",
            551 => "evHuntQuestProgressInfo",
            552 => "evHuntStarted",
            553 => "evHuntFinished",
            554 => "evHuntAborted",
            555 => "evHuntMissionStepStateUpdate",
            556 => "evNewHuntTrack",
            557 => "evHuntMissionUpdate",
            558 => "evHuntQuestMissionProgressUpdate",
            559 => "evHuntTrackUsed",
            560 => "evHuntTrackUseableAgain",
            561 => "evMinimapHuntTrackMarkers",
            562 => "evNoTracksFound",
            563 => "evHuntQuestAborted",
            564 => "evInteractWithTrackStart",
            565 => "evInteractWithTrackCancel",
            566 => "evInteractWithTrackFinished",
            567 => "evNewDynamicCompound",
            568 => "evLegendaryItemDestroyed",
            569 => "evAttunementInfo",
            570 => "evTerritoryClaimRaidedRawEnergyCrystalResult",
            571 => "evCarriedObjectExpiryWarning",
            572 => "evCarriedObjectExpired",
            573 => "evTerritoryRaidStart",
            574 => "evTerritoryRaidCancel",
            575 => "evTerritoryRaidFinished",
            576 => "evTerritoryRaidResult",
            577 => "evTerritoryMonolithActiveRaidStatus",
            578 => "evTerritoryMonolithActiveRaidCancelled",
            579 => "evMonolithEnergyStorageUpdate",
            580 => "evMonolithNextScheduledOpenWorldAttackUpdate",
            581 => "evMonolithProtectedBuildingsDamageReductionUpdate",
            582 => "evNewBuildingBaseEvent",
            583 => "evNewFortificationBuilding",
            584 => "evNewCastleGateBuilding",
            585 => "evBuildingDurabilityUpdate",
            586 => "evMonolithFortificationPointsUpdate",
            587 => "evFortificationBuildingUpgradeInfo",
            588 => "evFortificationBuildingsDamageStateUpdate",
            589 => "evSiegeNotificationEvent",
            590 => "evUpdateEnemyWarBannerActive",
            591 => "evTerritoryAnnouncePlayerEjection",
            592 => "evCastleGateSwitchUseStarted",
            593 => "evCastleGateSwitchUseFinished",
            594 => "evFortificationBuildingWillDowngrade",
            595 => "evBotCommand",
            596 => "evJournalAchievementProgressUpdate",
            597 => "evJournalClaimableRewardUpdate",
            598 => "evKeySync",
            599 => "evLocalQuestAreaGone",
            600 => "evDynamicTemplate",
            601 => "evDynamicTemplateForcedStateChange",
            602 => "evNewOutlandsTeleportationPortal",
            603 => "evNewOutlandsTeleportationReturnPortal",
            604 => "evOutlandsTeleportationBindingCleared",
            605 => "evOutlandsTeleportationReturnPortalUpdateEvent",
            606 => "evPlayerUsedOutlandsTeleportationPortal",
            607 => "evEncumberedRestricted",
            608 => "evNewPiledObject",
            609 => "evPiledObjectStateChanged",
            610 => "evNewSmugglerCrateDeliveryStation",
            611 => "evKillRewardedNoFame",
            612 => "evPickupFromPiledObjectStart",
            613 => "evPickupFromPiledObjectCancel",
            614 => "evPickupFromPiledObjectReset",
            615 => "evPickupFromPiledObjectFinished",
            616 => "evArmoryActivityChange",
            617 => "evNewKillTrophyFurnitureBuilding",
            618 => "evHellDungeonsPlayerJoinedInfo",
            619 => "evNewTileSwitchTrigger",
            620 => "evNewMultiRewardObject",
            621 => "evNewHellDungeonSoulShrineObject",
            622 => "evHellDungeonSoulShrineStateUpdate",
            623 => "evNewResurrectionShrine",
            624 => "evUpdateResurrectionShrine",
            625 => "evStandTimeFinished",
            626 => "evEpicAchievementAndStatsUpdate",
            627 => "evSpectateTargetAfterDeathUpdate",
            628 => "evSpectateTargetAfterDeathEnded",
            629 => "evNewHellDungeonUpwardExit",
            630 => "evNewHellDungeonSoulExit",
            631 => "evNewHellDungeonDownwardExit",
            632 => "evNewHellDungeonChestExit",
            633 => "evNewCorruptedStaticEntrance",
            634 => "evNewHellDungeonStaticEntrance",
            635 => "evUpdateHellDungeonStaticEntranceState",
            636 => "evDebugTriggerHellDungeonShutdownStart",
            637 => "evFullJournalQuestInfo",
            638 => "evJournalQuestProgressInfo",
            639 => "evNewHellDungeonRoomShrineObject",
            640 => "evHellDungeonRoomShrineStateUpdate",
            641 => "evSimpleBehaviourBuildingStateUpdate",
            642 => "evSetTimeScaling",
            643 => "evStopTimeScaling",
            644 => "evKeyValidation",
            645 => "evPlayerJoinMapMarkerTimerStates",
            646 => "evNewMapMarkerTimer",
            647 => "evRemoveMapMarkerTimer",
            648 => "evNewFactionFortressObject",
            649 => "evFactionFortressAnnouncePlayerEjection",
            650 => "evRewardFactionWarfareSupply",
            651 => "evFactionCaptureAreaProgressUpdate",
            652 => "evFactionFortressClaimed",
            653 => "evFactionFortressWeaponCachesSpawned",
            654 => "evFactionFortressWeaponCacheClaimed",
            655 => "evFactionFortressFightStateUpdate",
            656 => "evFactionFortressCutoffFightStateUpdate",
            657 => "evFactionFortressFightEnded",
            658 => "evNewFactionWarfarePortal",
            659 => "evFactionPortalTargetUpdate",
            660 => "evFactionFortressFightStartedInRemoteClusterEvent",
            661 => "evFactionFortressFightFinishedInRemoteClusterEvent",
            662 => "evFactionDuchySupplyWarDefensiveVictoryEvent",
            663 => "evFactionDuchyReconnectedFromCutoffEvent",
            664 => "evFactionFortressCutoffFightCancelledByClusterOwnerChangeEvent",
            665 => "evFactionDuchyEnteredCutoffStateEvent",
            666 => "evLeaveProtectionStateUpdate",
            667 => "evRedZoneEventStandings",
            668 => "evNewFactionBattleStandardDeliveryStation",
            669 => "evNewLoreSnippetObject",
            670 => "evLoreSnippetObjectStateUpdate",
            671 => "evLoreSnippedClaimed",
            672 => "evLoreSnippetStatesChangedByCheat",
            673 => "evNewTeleporterNode",
            674 => "evTeleporterNodeStateChanged",
            675 => "evTeleporterConnectionsFullStateUpdate",
            676 => "evTeleporterConnectionStateChanged",
            677 => "evRetrieveCarriableObjectStart",
            678 => "evRetrieveCarriableObjectCancel",
            679 => "evRetrieveCarriableObjectReset",
            680 => "evRetrieveCarriableObjectFinished",
            681 => "evLosingCarriableObjectStart",
            682 => "evLosingCarriableObjectFinished",
            _ => return write!(f, "EventType({})", self.0),
        };
        f.write_str(name)
    }
}
