use std::collections::HashSet;
use std::fs;

fn main() {
    let xml = fs::read_to_string("crates/achievements-codegen/achievements.xml").expect("read XML");
    let doc = roxmltree::Document::parse(&xml).expect("parse XML");

    let mut entries = Vec::new();
    let mut seen = HashSet::new();

    for node in doc.root_element().children().filter(|n| n.is_element()) {
        let tag = node.tag_name().name();
        if tag != "achievement" && tag != "templateachievement" {
            continue;
        }
        let Some(id) = node.attribute("id") else {
            continue;
        };
        if !seen.insert(id) {
            continue;
        }
        let ring = node.attribute("ring").unwrap_or("");
        let max = if id.starts_with("COMBAT_") && ring == "9" {
            120
        } else {
            100
        };
        entries.push((id, max));
    }

    let mut lines = Vec::with_capacity(entries.len() + 3);
    lines.push("// Auto-generated by `cargo run -p achievements-codegen`.".to_string());
    lines.push("// Do not edit this file manually.".to_string());
    lines.push(format!(
        "pub const ACHIEVEMENTS: [(&str, u8); {}] = [",
        entries.len()
    ));
    for (id, max) in &entries {
        lines.push(format!("    (\"{}\", {}),", id, *max));
    }
    lines.push("];".to_string());

    let out_path = "crates/specs-exporter/src/achievements.rs";
    fs::write(out_path, lines.join("\n") + "\n").expect("write output");
    println!("Generated achievements in {}", out_path);
}
