#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct OperationType(pub u16);

#[allow(non_upper_case_globals)]
#[allow(dead_code)]
impl OperationType {
    pub const opUnused: OperationType = OperationType(0);
    pub const opPing: OperationType = OperationType(1);
    pub const opJoin: OperationType = OperationType(2);
    pub const opVersionedOperation: OperationType = OperationType(3);
    pub const opCreateAccount: OperationType = OperationType(4);
    pub const opLogin: OperationType = OperationType(5);
    pub const opCreateGuestAccount: OperationType = OperationType(6);
    pub const opCreatePlatformOnlyAccount: OperationType = OperationType(7);
    pub const opSendCrashLog: OperationType = OperationType(8);
    pub const opSendTraceRoute: OperationType = OperationType(9);
    pub const opSendVfxStats: OperationType = OperationType(10);
    pub const opSendGamePingInfo: OperationType = OperationType(11);
    pub const opCreateCharacter: OperationType = OperationType(12);
    pub const opDeleteCharacter: OperationType = OperationType(13);
    pub const opSelectCharacter: OperationType = OperationType(14);
    pub const opAcceptPopups: OperationType = OperationType(15);
    pub const opRedeemKeycode: OperationType = OperationType(16);
    pub const opGetGameServerByCluster: OperationType = OperationType(17);
    pub const opGetShopPurchaseUrl: OperationType = OperationType(18);
    pub const opGetReferralSeasonDetails: OperationType = OperationType(19);
    pub const opGetReferralLink: OperationType = OperationType(20);
    pub const opGetShopTilesForCategory: OperationType = OperationType(21);
    pub const opMove: OperationType = OperationType(22);
    pub const opAttackStart: OperationType = OperationType(23);
    pub const opCastStart: OperationType = OperationType(24);
    pub const opCastCancel: OperationType = OperationType(25);
    pub const opTerminateToggleSpell: OperationType = OperationType(26);
    pub const opChannelingCancel: OperationType = OperationType(27);
    pub const opAttackBuildingStart: OperationType = OperationType(28);
    pub const opInventoryDestroyItem: OperationType = OperationType(29);
    pub const opInventoryMoveItem: OperationType = OperationType(30);
    pub const opInventoryRecoverItem: OperationType = OperationType(31);
    pub const opInventoryRecoverAllItems: OperationType = OperationType(32);
    pub const opInventorySplitStack: OperationType = OperationType(33);
    pub const opInventorySplitStackInto: OperationType = OperationType(34);
    pub const opInventoryStack: OperationType = OperationType(35);
    pub const opInventoryReorder: OperationType = OperationType(36);
    pub const opInventoryDropAll: OperationType = OperationType(37);
    pub const opInventoryAddToStacks: OperationType = OperationType(38);
    pub const opInventoryMoveGivenItems: OperationType = OperationType(39);
    pub const opGetClusterData: OperationType = OperationType(40);
    pub const opChangeCluster: OperationType = OperationType(41);
    pub const opConsoleCommand: OperationType = OperationType(42);
    pub const opChatMessage: OperationType = OperationType(43);
    pub const opReportClientError: OperationType = OperationType(44);
    pub const opRegisterToObject: OperationType = OperationType(45);
    pub const opUnRegisterFromObject: OperationType = OperationType(46);
    pub const opCraftBuildingChangeSettings: OperationType = OperationType(47);
    pub const opCraftBuildingTakeMoney: OperationType = OperationType(48);
    pub const opRepairBuildingChangeSettings: OperationType = OperationType(49);
    pub const opRepairBuildingTakeMoney: OperationType = OperationType(50);
    pub const opActionBuildingChangeSettings: OperationType = OperationType(51);
    pub const opHarvestStart: OperationType = OperationType(52);
    pub const opHarvestCancel: OperationType = OperationType(53);
    pub const opTakeSilver: OperationType = OperationType(54);
    pub const opActionOnBuildingStart: OperationType = OperationType(55);
    pub const opActionOnBuildingCancel: OperationType = OperationType(56);
    pub const opInstallResourceStart: OperationType = OperationType(57);
    pub const opInstallResourceCancel: OperationType = OperationType(58);
    pub const opInstallSilver: OperationType = OperationType(59);
    pub const opBuildingFillNutrition: OperationType = OperationType(60);
    pub const opBuildingChangeRenovationState: OperationType = OperationType(61);
    pub const opBuildingBuySkin: OperationType = OperationType(62);
    pub const opBuildingClaim: OperationType = OperationType(63);
    pub const opBuildingGiveup: OperationType = OperationType(64);
    pub const opBuildingNutritionSilverStorageDeposit: OperationType = OperationType(65);
    pub const opBuildingNutritionSilverStorageWithdraw: OperationType = OperationType(66);
    pub const opBuildingNutritionSilverRewardSet: OperationType = OperationType(67);
    pub const opConstructionSiteCreate: OperationType = OperationType(68);
    pub const opPlaceableObjectPlace: OperationType = OperationType(69);
    pub const opPlaceableObjectPlaceCancel: OperationType = OperationType(70);
    pub const opPlaceableObjectPickup: OperationType = OperationType(71);
    pub const opFurnitureObjectUse: OperationType = OperationType(72);
    pub const opFarmableHarvest: OperationType = OperationType(73);
    pub const opFarmableFinishGrownItem: OperationType = OperationType(74);
    pub const opFarmableDestroy: OperationType = OperationType(75);
    pub const opFarmableGetProduct: OperationType = OperationType(76);
    pub const opFarmableFill: OperationType = OperationType(77);
    pub const opTearDownConstructionSite: OperationType = OperationType(78);
    pub const opAuctionCreateOffer: OperationType = OperationType(79);
    pub const opAuctionCreateRequest: OperationType = OperationType(80);
    pub const opAuctionGetOffers: OperationType = OperationType(81);
    pub const opAuctionGetRequests: OperationType = OperationType(82);
    pub const opAuctionBuyOffer: OperationType = OperationType(83);
    pub const opAuctionAbortAuction: OperationType = OperationType(84);
    pub const opAuctionModifyAuction: OperationType = OperationType(85);
    pub const opAuctionAbortOffer: OperationType = OperationType(86);
    pub const opAuctionAbortRequest: OperationType = OperationType(87);
    pub const opAuctionSellRequest: OperationType = OperationType(88);
    pub const opAuctionGetFinishedAuctions: OperationType = OperationType(89);
    pub const opAuctionGetFinishedAuctionsCount: OperationType = OperationType(90);
    pub const opAuctionFetchAuction: OperationType = OperationType(91);
    pub const opAuctionGetMyOpenOffers: OperationType = OperationType(92);
    pub const opAuctionGetMyOpenRequests: OperationType = OperationType(93);
    pub const opAuctionGetMyOpenAuctions: OperationType = OperationType(94);
    pub const opAuctionGetItemAverageStats: OperationType = OperationType(95);
    pub const opAuctionGetItemAverageValue: OperationType = OperationType(96);
    pub const opAuctionGetLowestOfferPrices: OperationType = OperationType(97);
    pub const opContainerOpen: OperationType = OperationType(98);
    pub const opContainerClose: OperationType = OperationType(99);
    pub const opContainerManageSubContainer: OperationType = OperationType(100);
    pub const opRespawn: OperationType = OperationType(101);
    pub const opSuicide: OperationType = OperationType(102);
    pub const opJoinGuild: OperationType = OperationType(103);
    pub const opLeaveGuild: OperationType = OperationType(104);
    pub const opCreateGuild: OperationType = OperationType(105);
    pub const opInviteToGuild: OperationType = OperationType(106);
    pub const opDeclineGuildInvitation: OperationType = OperationType(107);
    pub const opKickFromGuild: OperationType = OperationType(108);
    pub const opInstantJoinGuild: OperationType = OperationType(109);
    pub const opDuellingChallengePlayer: OperationType = OperationType(110);
    pub const opDuellingAcceptChallenge: OperationType = OperationType(111);
    pub const opDuellingDenyChallenge: OperationType = OperationType(112);
    pub const opChangeClusterTax: OperationType = OperationType(113);
    pub const opClaimTerritory: OperationType = OperationType(114);
    pub const opGiveUpTerritory: OperationType = OperationType(115);
    pub const opChangeTerritoryAccessRights: OperationType = OperationType(116);
    pub const opGetMonolithInfo: OperationType = OperationType(117);
    pub const opGetClaimInfo: OperationType = OperationType(118);
    pub const opGetAttackInfo: OperationType = OperationType(119);
    pub const opGetTerritorySeasonPoints: OperationType = OperationType(120);
    pub const opGetAttackSchedule: OperationType = OperationType(121);
    pub const opGetMatches: OperationType = OperationType(122);
    pub const opGetMatchDetails: OperationType = OperationType(123);
    pub const opJoinMatch: OperationType = OperationType(124);
    pub const opLeaveMatch: OperationType = OperationType(125);
    pub const opGetClusterInstanceInfoForStaticCluster: OperationType = OperationType(126);
    pub const opChangeChatSettings: OperationType = OperationType(127);
    pub const opLogoutStart: OperationType = OperationType(128);
    pub const opLogoutCancel: OperationType = OperationType(129);
    pub const opClaimOrbStart: OperationType = OperationType(130);
    pub const opClaimOrbCancel: OperationType = OperationType(131);
    pub const opMatchLootChestOpeningStart: OperationType = OperationType(132);
    pub const opMatchLootChestOpeningCancel: OperationType = OperationType(133);
    pub const opDepositToGuildAccount: OperationType = OperationType(134);
    pub const opWithdrawalFromAccount: OperationType = OperationType(135);
    pub const opChangeGuildPayUpkeepFlag: OperationType = OperationType(136);
    pub const opChangeGuildTax: OperationType = OperationType(137);
    pub const opGetMyTerritories: OperationType = OperationType(138);
    pub const opMorganaCommand: OperationType = OperationType(139);
    pub const opGetServerInfo: OperationType = OperationType(140);
    pub const opSubscribeToCluster: OperationType = OperationType(141);
    pub const opAnswerMercenaryInvitation: OperationType = OperationType(142);
    pub const opGetCharacterEquipment: OperationType = OperationType(143);
    pub const opGetCharacterSteamAchievements: OperationType = OperationType(144);
    pub const opGetCharacterStats: OperationType = OperationType(145);
    pub const opGetKillHistoryDetails: OperationType = OperationType(146);
    pub const opReSpecAchievement: OperationType = OperationType(147);
    pub const opChangeAvatar: OperationType = OperationType(148);
    pub const opGetRankings: OperationType = OperationType(149);
    pub const opGetRank: OperationType = OperationType(150);
    pub const opGetGvgSeasonRankings: OperationType = OperationType(151);
    pub const opGetGvgSeasonRank: OperationType = OperationType(152);
    pub const opGetGvgSeasonHistoryRankings: OperationType = OperationType(153);
    pub const opGetGvgSeasonGuildMemberHistory: OperationType = OperationType(154);
    pub const opKickFromGvGMatch: OperationType = OperationType(155);
    pub const opGetCrystalLeagueDailySeasonPoints: OperationType = OperationType(156);
    pub const opGetChestLogs: OperationType = OperationType(157);
    pub const opGetAccessRightLogs: OperationType = OperationType(158);
    pub const opGetGuildAccountLogs: OperationType = OperationType(159);
    pub const opGetGuildAccountLogsLargeAmount: OperationType = OperationType(160);
    pub const opInviteToPlayerTrade: OperationType = OperationType(161);
    pub const opPlayerTradeCancel: OperationType = OperationType(162);
    pub const opPlayerTradeInvitationAccept: OperationType = OperationType(163);
    pub const opPlayerTradeAddItem: OperationType = OperationType(164);
    pub const opPlayerTradeRemoveItem: OperationType = OperationType(165);
    pub const opPlayerTradeAcceptTrade: OperationType = OperationType(166);
    pub const opPlayerTradeSetSilverOrGold: OperationType = OperationType(167);
    pub const opSendMiniMapPing: OperationType = OperationType(168);
    pub const opStuck: OperationType = OperationType(169);
    pub const opBuyRealEstate: OperationType = OperationType(170);
    pub const opClaimRealEstate: OperationType = OperationType(171);
    pub const opGiveUpRealEstate: OperationType = OperationType(172);
    pub const opChangeRealEstateOutline: OperationType = OperationType(173);
    pub const opGetMailInfos: OperationType = OperationType(174);
    pub const opGetMailCount: OperationType = OperationType(175);
    pub const opReadMail: OperationType = OperationType(176);
    pub const opSendNewMail: OperationType = OperationType(177);
    pub const opDeleteMail: OperationType = OperationType(178);
    pub const opMarkMailUnread: OperationType = OperationType(179);
    pub const opClaimAttachmentFromMail: OperationType = OperationType(180);
    pub const opApplyToGuild: OperationType = OperationType(181);
    pub const opAnswerGuildApplication: OperationType = OperationType(182);
    pub const opRequestGuildFinderFilteredList: OperationType = OperationType(183);
    pub const opUpdateGuildRecruitmentInfo: OperationType = OperationType(184);
    pub const opRequestGuildRecruitmentInfo: OperationType = OperationType(185);
    pub const opRequestGuildFinderNameSearch: OperationType = OperationType(186);
    pub const opRequestGuildFinderRecommendedList: OperationType = OperationType(187);
    pub const opRegisterChatPeer: OperationType = OperationType(188);
    pub const opSendChatMessage: OperationType = OperationType(189);
    pub const opSendModeratorMessage: OperationType = OperationType(190);
    pub const opJoinChatChannel: OperationType = OperationType(191);
    pub const opLeaveChatChannel: OperationType = OperationType(192);
    pub const opSendWhisperMessage: OperationType = OperationType(193);
    pub const opSay: OperationType = OperationType(194);
    pub const opPlayEmote: OperationType = OperationType(195);
    pub const opStopEmote: OperationType = OperationType(196);
    pub const opGetClusterMapInfo: OperationType = OperationType(197);
    pub const opAccessRightsChangeSettings: OperationType = OperationType(198);
    pub const opMount: OperationType = OperationType(199);
    pub const opMountCancel: OperationType = OperationType(200);
    pub const opBuyJourney: OperationType = OperationType(201);
    pub const opSetSaleStatusForEstate: OperationType = OperationType(202);
    pub const opResolveGuildOrPlayerName: OperationType = OperationType(203);
    pub const opGetRespawnInfos: OperationType = OperationType(204);
    pub const opMakeHome: OperationType = OperationType(205);
    pub const opLeaveHome: OperationType = OperationType(206);
    pub const opResurrectionReply: OperationType = OperationType(207);
    pub const opAllianceCreate: OperationType = OperationType(208);
    pub const opAllianceDisband: OperationType = OperationType(209);
    pub const opAllianceGetMemberInfos: OperationType = OperationType(210);
    pub const opAllianceInvite: OperationType = OperationType(211);
    pub const opAllianceAnswerInvitation: OperationType = OperationType(212);
    pub const opAllianceCancelInvitation: OperationType = OperationType(213);
    pub const opAllianceKickGuild: OperationType = OperationType(214);
    pub const opAllianceLeave: OperationType = OperationType(215);
    pub const opAllianceChangeGoldPaymentFlag: OperationType = OperationType(216);
    pub const opAllianceGetDetailInfo: OperationType = OperationType(217);
    pub const opGetIslandInfos: OperationType = OperationType(218);
    pub const opBuyMyIsland: OperationType = OperationType(219);
    pub const opBuyGuildIsland: OperationType = OperationType(220);
    pub const opUpgradeMyIsland: OperationType = OperationType(221);
    pub const opUpgradeGuildIsland: OperationType = OperationType(222);
    pub const opTerritoryFillNutrition: OperationType = OperationType(223);
    pub const opTeleportBack: OperationType = OperationType(224);
    pub const opPartyInvitePlayer: OperationType = OperationType(225);
    pub const opPartyRequestJoin: OperationType = OperationType(226);
    pub const opPartyAnswerInvitation: OperationType = OperationType(227);
    pub const opPartyAnswerJoinRequest: OperationType = OperationType(228);
    pub const opPartyLeave: OperationType = OperationType(229);
    pub const opPartyKickPlayer: OperationType = OperationType(230);
    pub const opPartyMakeLeader: OperationType = OperationType(231);
    pub const opPartyChangeLootSetting: OperationType = OperationType(232);
    pub const opPartyMarkObject: OperationType = OperationType(233);
    pub const opPartySetRole: OperationType = OperationType(234);
    pub const opPartyChangeFactionWarfareRequestReinforcementsSetting: OperationType =
        OperationType(235);
    pub const opSetGuildCodex: OperationType = OperationType(236);
    pub const opExitEnterStart: OperationType = OperationType(237);
    pub const opExitEnterCancel: OperationType = OperationType(238);
    pub const opQuestGiverRequest: OperationType = OperationType(239);
    pub const opGoldMarketGetBuyOffer: OperationType = OperationType(240);
    pub const opGoldMarketGetBuyOfferFromSilver: OperationType = OperationType(241);
    pub const opGoldMarketGetSellOffer: OperationType = OperationType(242);
    pub const opGoldMarketGetSellOfferFromSilver: OperationType = OperationType(243);
    pub const opGoldMarketBuyGold: OperationType = OperationType(244);
    pub const opGoldMarketSellGold: OperationType = OperationType(245);
    pub const opGoldMarketCreateSellOrder: OperationType = OperationType(246);
    pub const opGoldMarketCreateBuyOrder: OperationType = OperationType(247);
    pub const opGoldMarketGetInfos: OperationType = OperationType(248);
    pub const opGoldMarketCancelOrder: OperationType = OperationType(249);
    pub const opGoldMarketGetAverageInfo: OperationType = OperationType(250);
    pub const opTreasureChestUsingStart: OperationType = OperationType(251);
    pub const opTreasureChestUsingCancel: OperationType = OperationType(252);
    pub const opUseLootChest: OperationType = OperationType(253);
    pub const opUseShrine: OperationType = OperationType(254);
    pub const opGetSiegeBannerInfo: OperationType = OperationType(255);
    pub const opLaborerStartJob: OperationType = OperationType(256);
    pub const opLaborerTakeJobLoot: OperationType = OperationType(257);
    pub const opLaborerDismiss: OperationType = OperationType(258);
    pub const opLaborerMove: OperationType = OperationType(259);
    pub const opLaborerBuyItem: OperationType = OperationType(260);
    pub const opLaborerUpgrade: OperationType = OperationType(261);
    pub const opBuyPremium: OperationType = OperationType(262);
    pub const opRealEstateGetAuctionData: OperationType = OperationType(263);
    pub const opRealEstateBidOnAuction: OperationType = OperationType(264);
}

impl std::fmt::Display for OperationType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let name = match self.0 {
            0 => "opUnused",
            1 => "opPing",
            2 => "opJoin",
            3 => "opVersionedOperation",
            4 => "opCreateAccount",
            5 => "opLogin",
            6 => "opCreateGuestAccount",
            7 => "opCreatePlatformOnlyAccount",
            8 => "opSendCrashLog",
            9 => "opSendTraceRoute",
            10 => "opSendVfxStats",
            11 => "opSendGamePingInfo",
            12 => "opCreateCharacter",
            13 => "opDeleteCharacter",
            14 => "opSelectCharacter",
            15 => "opAcceptPopups",
            16 => "opRedeemKeycode",
            17 => "opGetGameServerByCluster",
            18 => "opGetShopPurchaseUrl",
            19 => "opGetReferralSeasonDetails",
            20 => "opGetReferralLink",
            21 => "opGetShopTilesForCategory",
            22 => "opMove",
            23 => "opAttackStart",
            24 => "opCastStart",
            25 => "opCastCancel",
            26 => "opTerminateToggleSpell",
            27 => "opChannelingCancel",
            28 => "opAttackBuildingStart",
            29 => "opInventoryDestroyItem",
            30 => "opInventoryMoveItem",
            31 => "opInventoryRecoverItem",
            32 => "opInventoryRecoverAllItems",
            33 => "opInventorySplitStack",
            34 => "opInventorySplitStackInto",
            35 => "opInventoryStack",
            36 => "opInventoryReorder",
            37 => "opInventoryDropAll",
            38 => "opInventoryAddToStacks",
            39 => "opInventoryMoveGivenItems",
            40 => "opGetClusterData",
            41 => "opChangeCluster",
            42 => "opConsoleCommand",
            43 => "opChatMessage",
            44 => "opReportClientError",
            45 => "opRegisterToObject",
            46 => "opUnRegisterFromObject",
            47 => "opCraftBuildingChangeSettings",
            48 => "opCraftBuildingTakeMoney",
            49 => "opRepairBuildingChangeSettings",
            50 => "opRepairBuildingTakeMoney",
            51 => "opActionBuildingChangeSettings",
            52 => "opHarvestStart",
            53 => "opHarvestCancel",
            54 => "opTakeSilver",
            55 => "opActionOnBuildingStart",
            56 => "opActionOnBuildingCancel",
            57 => "opInstallResourceStart",
            58 => "opInstallResourceCancel",
            59 => "opInstallSilver",
            60 => "opBuildingFillNutrition",
            61 => "opBuildingChangeRenovationState",
            62 => "opBuildingBuySkin",
            63 => "opBuildingClaim",
            64 => "opBuildingGiveup",
            65 => "opBuildingNutritionSilverStorageDeposit",
            66 => "opBuildingNutritionSilverStorageWithdraw",
            67 => "opBuildingNutritionSilverRewardSet",
            68 => "opConstructionSiteCreate",
            69 => "opPlaceableObjectPlace",
            70 => "opPlaceableObjectPlaceCancel",
            71 => "opPlaceableObjectPickup",
            72 => "opFurnitureObjectUse",
            73 => "opFarmableHarvest",
            74 => "opFarmableFinishGrownItem",
            75 => "opFarmableDestroy",
            76 => "opFarmableGetProduct",
            77 => "opFarmableFill",
            78 => "opTearDownConstructionSite",
            79 => "opAuctionCreateOffer",
            80 => "opAuctionCreateRequest",
            81 => "opAuctionGetOffers",
            82 => "opAuctionGetRequests",
            83 => "opAuctionBuyOffer",
            84 => "opAuctionAbortAuction",
            85 => "opAuctionModifyAuction",
            86 => "opAuctionAbortOffer",
            87 => "opAuctionAbortRequest",
            88 => "opAuctionSellRequest",
            89 => "opAuctionGetFinishedAuctions",
            90 => "opAuctionGetFinishedAuctionsCount",
            91 => "opAuctionFetchAuction",
            92 => "opAuctionGetMyOpenOffers",
            93 => "opAuctionGetMyOpenRequests",
            94 => "opAuctionGetMyOpenAuctions",
            95 => "opAuctionGetItemAverageStats",
            96 => "opAuctionGetItemAverageValue",
            97 => "opAuctionGetLowestOfferPrices",
            98 => "opContainerOpen",
            99 => "opContainerClose",
            100 => "opContainerManageSubContainer",
            101 => "opRespawn",
            102 => "opSuicide",
            103 => "opJoinGuild",
            104 => "opLeaveGuild",
            105 => "opCreateGuild",
            106 => "opInviteToGuild",
            107 => "opDeclineGuildInvitation",
            108 => "opKickFromGuild",
            109 => "opInstantJoinGuild",
            110 => "opDuellingChallengePlayer",
            111 => "opDuellingAcceptChallenge",
            112 => "opDuellingDenyChallenge",
            113 => "opChangeClusterTax",
            114 => "opClaimTerritory",
            115 => "opGiveUpTerritory",
            116 => "opChangeTerritoryAccessRights",
            117 => "opGetMonolithInfo",
            118 => "opGetClaimInfo",
            119 => "opGetAttackInfo",
            120 => "opGetTerritorySeasonPoints",
            121 => "opGetAttackSchedule",
            122 => "opGetMatches",
            123 => "opGetMatchDetails",
            124 => "opJoinMatch",
            125 => "opLeaveMatch",
            126 => "opGetClusterInstanceInfoForStaticCluster",
            127 => "opChangeChatSettings",
            128 => "opLogoutStart",
            129 => "opLogoutCancel",
            130 => "opClaimOrbStart",
            131 => "opClaimOrbCancel",
            132 => "opMatchLootChestOpeningStart",
            133 => "opMatchLootChestOpeningCancel",
            134 => "opDepositToGuildAccount",
            135 => "opWithdrawalFromAccount",
            136 => "opChangeGuildPayUpkeepFlag",
            137 => "opChangeGuildTax",
            138 => "opGetMyTerritories",
            139 => "opMorganaCommand",
            140 => "opGetServerInfo",
            141 => "opSubscribeToCluster",
            142 => "opAnswerMercenaryInvitation",
            143 => "opGetCharacterEquipment",
            144 => "opGetCharacterSteamAchievements",
            145 => "opGetCharacterStats",
            146 => "opGetKillHistoryDetails",
            147 => "opReSpecAchievement",
            148 => "opChangeAvatar",
            149 => "opGetRankings",
            150 => "opGetRank",
            151 => "opGetGvgSeasonRankings",
            152 => "opGetGvgSeasonRank",
            153 => "opGetGvgSeasonHistoryRankings",
            154 => "opGetGvgSeasonGuildMemberHistory",
            155 => "opKickFromGvGMatch",
            156 => "opGetCrystalLeagueDailySeasonPoints",
            157 => "opGetChestLogs",
            158 => "opGetAccessRightLogs",
            159 => "opGetGuildAccountLogs",
            160 => "opGetGuildAccountLogsLargeAmount",
            161 => "opInviteToPlayerTrade",
            162 => "opPlayerTradeCancel",
            163 => "opPlayerTradeInvitationAccept",
            164 => "opPlayerTradeAddItem",
            165 => "opPlayerTradeRemoveItem",
            166 => "opPlayerTradeAcceptTrade",
            167 => "opPlayerTradeSetSilverOrGold",
            168 => "opSendMiniMapPing",
            169 => "opStuck",
            170 => "opBuyRealEstate",
            171 => "opClaimRealEstate",
            172 => "opGiveUpRealEstate",
            173 => "opChangeRealEstateOutline",
            174 => "opGetMailInfos",
            175 => "opGetMailCount",
            176 => "opReadMail",
            177 => "opSendNewMail",
            178 => "opDeleteMail",
            179 => "opMarkMailUnread",
            180 => "opClaimAttachmentFromMail",
            181 => "opApplyToGuild",
            182 => "opAnswerGuildApplication",
            183 => "opRequestGuildFinderFilteredList",
            184 => "opUpdateGuildRecruitmentInfo",
            185 => "opRequestGuildRecruitmentInfo",
            186 => "opRequestGuildFinderNameSearch",
            187 => "opRequestGuildFinderRecommendedList",
            188 => "opRegisterChatPeer",
            189 => "opSendChatMessage",
            190 => "opSendModeratorMessage",
            191 => "opJoinChatChannel",
            192 => "opLeaveChatChannel",
            193 => "opSendWhisperMessage",
            194 => "opSay",
            195 => "opPlayEmote",
            196 => "opStopEmote",
            197 => "opGetClusterMapInfo",
            198 => "opAccessRightsChangeSettings",
            199 => "opMount",
            200 => "opMountCancel",
            201 => "opBuyJourney",
            202 => "opSetSaleStatusForEstate",
            203 => "opResolveGuildOrPlayerName",
            204 => "opGetRespawnInfos",
            205 => "opMakeHome",
            206 => "opLeaveHome",
            207 => "opResurrectionReply",
            208 => "opAllianceCreate",
            209 => "opAllianceDisband",
            210 => "opAllianceGetMemberInfos",
            211 => "opAllianceInvite",
            212 => "opAllianceAnswerInvitation",
            213 => "opAllianceCancelInvitation",
            214 => "opAllianceKickGuild",
            215 => "opAllianceLeave",
            216 => "opAllianceChangeGoldPaymentFlag",
            217 => "opAllianceGetDetailInfo",
            218 => "opGetIslandInfos",
            219 => "opBuyMyIsland",
            220 => "opBuyGuildIsland",
            221 => "opUpgradeMyIsland",
            222 => "opUpgradeGuildIsland",
            223 => "opTerritoryFillNutrition",
            224 => "opTeleportBack",
            225 => "opPartyInvitePlayer",
            226 => "opPartyRequestJoin",
            227 => "opPartyAnswerInvitation",
            228 => "opPartyAnswerJoinRequest",
            229 => "opPartyLeave",
            230 => "opPartyKickPlayer",
            231 => "opPartyMakeLeader",
            232 => "opPartyChangeLootSetting",
            233 => "opPartyMarkObject",
            234 => "opPartySetRole",
            235 => "opPartyChangeFactionWarfareRequestReinforcementsSetting",
            236 => "opSetGuildCodex",
            237 => "opExitEnterStart",
            238 => "opExitEnterCancel",
            239 => "opQuestGiverRequest",
            240 => "opGoldMarketGetBuyOffer",
            241 => "opGoldMarketGetBuyOfferFromSilver",
            242 => "opGoldMarketGetSellOffer",
            243 => "opGoldMarketGetSellOfferFromSilver",
            244 => "opGoldMarketBuyGold",
            245 => "opGoldMarketSellGold",
            246 => "opGoldMarketCreateSellOrder",
            247 => "opGoldMarketCreateBuyOrder",
            248 => "opGoldMarketGetInfos",
            249 => "opGoldMarketCancelOrder",
            250 => "opGoldMarketGetAverageInfo",
            251 => "opTreasureChestUsingStart",
            252 => "opTreasureChestUsingCancel",
            253 => "opUseLootChest",
            254 => "opUseShrine",
            255 => "opGetSiegeBannerInfo",
            256 => "opLaborerStartJob",
            257 => "opLaborerTakeJobLoot",
            258 => "opLaborerDismiss",
            259 => "opLaborerMove",
            260 => "opLaborerBuyItem",
            261 => "opLaborerUpgrade",
            262 => "opBuyPremium",
            263 => "opRealEstateGetAuctionData",
            264 => "opRealEstateBidOnAuction",
            _ => return write!(f, "OperationType({})", self.0),
        };
        f.write_str(name)
    }
}
