name: CI
on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    name: ${{ matrix.os }}-latest
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu
          - os: macos
          - os: windows

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install libpcap (Ubuntu)
        if: matrix.os == 'ubuntu'
        run: sudo apt-get update -y && sudo apt-get install -y libpcap-dev

      - name: Install Npcap SDK (Windows)
        if: matrix.os == 'windows'
        run: |
          Invoke-WebRequest -Uri "https://npcap.com/dist/npcap-sdk-1.16.zip" -OutFile "C:/npcap-sdk.zip"
          Expand-Archive -LiteralPath C:/npcap-sdk.zip -DestinationPath C:/npcap-sdk
          echo "LIB=C:/npcap-sdk/Lib/x64" >> $env:GITHUB_ENV

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build --workspace --verbose

      - name: Run clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
